export const ListOrderService = { 
    getListOrderData() { 
        return [
            {
                id: 1,
                etenUserListID: 'E346572',
                etenUserID: 'EU1001',
                custAccountNo: '6080100900',
                companyName: 'PS Tyres & Battery Auto Services Sdn. Bhd',
                salesOrg: '1000',
                distributionChannel: '10',
                division: '01',
                priceGroup: 'PG1',
                sapOrderType: 'OT01',
                customerCondGrp: 'C1',
                shipTo: 'SHIP01',
                shippingCond: '01',
                storageLocation: 'SL01',
                orderDesc: 'NORMAL',
                channel: 'ETEN',
                containerSize: '20FT',
                deliveryType: 'DELIVER',
                deliveryDate: '2025-10-05',
                eten_user_shiptoID: 'SHP1001',
                orderNo: 'ORD001',
                soNo: 'SO001',
                doNo: 'DO001',
                invNo: 'INV001',
                order_array: ['item1','item2'],
                fullfill_order_array: ['fulfilled1'],
                subtotal: 1000.00,
                tax: 60.00,
                total: 1060.00,
                orderReceiveRating: 5,
                orderReceiveRemarks: 'Good delivery',
                orderStatus: 1, // completed
                sap_timestamp: '2025-10-02T10:00:00Z',
                created: '2025-10-02T09:00:00Z'
            },
            {
                id: 2,
                etenUserListID: 'E234176',
                etenUserID: 'EU1002',
                custAccountNo: '6080102300',
                companyName: '',
                salesOrg: '1000',
                distributionChannel: '20',
                division: '01',
                priceGroup: 'PG2',
                sapOrderType: 'OT02',
                customerCondGrp: 'C2',
                shipTo: 'SHIP02',
                shippingCond: '02',
                storageLocation: 'SL02',
                orderDesc: 'DIRECTSHIP',
                channel: 'ADMIN',
                containerSize: '40FT',
                deliveryType: 'SELFCOLLECT',
                deliveryDate: '2025-10-07',
                eten_user_shiptoID: 'SHP1002',
                orderNo: 'ORD002',
                soNo: 'SO002',
                doNo: 'DO002',
                invNo: 'INV002',
                order_array: ['item3'],
                fullfill_order_array: ['fulfilled3'],
                subtotal: 2000.00,
                tax: 120.00,
                total: 2120.00,
                orderReceiveRating: 4,
                orderReceiveRemarks: 'Self collect',
                orderStatus: 66, // processing
                sap_timestamp: '2025-10-02T11:00:00Z',
                created: '2025-10-02T09:30:00Z'
            },
            {
                id: 3,
                etenUserListID: 'E127568',
                etenUserID: 'EU1003',
                custAccountNo: '6080102301',
                companyName: '',
                salesOrg: '2000',
                distributionChannel: '10',
                division: '02',
                priceGroup: 'PG3',
                sapOrderType: 'OT03',
                customerCondGrp: 'C3',
                shipTo: 'SHIP03',
                shippingCond: '03',
                storageLocation: 'SL03',
                orderDesc: 'OWN',
                channel: 'CARES',
                containerSize: '10FT',
                deliveryType: 'LALAMOVE',
                deliveryDate: '2025-10-10',
                eten_user_shiptoID: 'SHP1003',
                orderNo: 'ORD003',
                soNo: 'SO003',
                doNo: 'DO003',
                invNo: 'INV003',
                order_array: ['item4','item5','item6'],
                fullfill_order_array: ['fulfilled4','fulfilled5'],
                subtotal: 1500.00,
                tax: 90.00,
                total: 1590.00,
                orderReceiveRating: 3,
                orderReceiveRemarks: 'Delay',
                orderStatus: 77, // delivery
                sap_timestamp: '2025-10-02T12:00:00Z',
                created: '2025-10-02T09:45:00Z'
            },
            {
                id: 4,
                etenUserListID: 'E127823',
                etenUserID: 'EU1004',
                custAccountNo: '6080102302',
                companyName: '',
                salesOrg: '2000',
                distributionChannel: '30',
                division: '01',
                priceGroup: 'PG4',
                sapOrderType: 'OT04',
                customerCondGrp: 'C4',
                shipTo: 'SHIP04',
                shippingCond: '04',
                storageLocation: 'SL04',
                orderDesc: 'NORMAL',
                channel: 'ETEN',
                containerSize: '20FT',
                deliveryType: 'DELIVER',
                deliveryDate: '2025-10-12',
                eten_user_shiptoID: 'SHP1004',
                orderNo: 'ORD004',
                soNo: 'SO004',
                doNo: 'DO004',
                invNo: 'INV004',
                order_array: ['item7'],
                fullfill_order_array: ['fulfilled7'],
                subtotal: 3000.00,
                tax: 180.00,
                total: 3180.00,
                orderReceiveRating: 5,
                orderReceiveRemarks: 'Fast delivery',
                orderStatus: 1,
                sap_timestamp: '2025-10-02T12:30:00Z',
                created: '2025-10-02T10:15:00Z'
            },
            {
                id: 5,
                etenUserListID: 'E74B23S5',
                etenUserID: 'EU1005',
                custAccountNo: '6080114400',
                companyName: '',
                salesOrg: '3000',
                distributionChannel: '40',
                division: '02',
                priceGroup: 'PG5',
                sapOrderType: 'OT05',
                customerCondGrp: 'C5',
                shipTo: 'SHIP05',
                shippingCond: '05',
                storageLocation: 'SL05',
                orderDesc: 'DIRECTSHIP',
                channel: 'ADMIN',
                containerSize: '40FT',
                deliveryType: 'DELIVER',
                deliveryDate: '2025-10-15',
                eten_user_shiptoID: 'SHP1005',
                orderNo: 'ORD005',
                soNo: 'SO005',
                doNo: 'DO005',
                invNo: 'INV005',
                order_array: ['item8','item9'],
                fullfill_order_array: ['fulfilled8'],
                subtotal: 2500.00,
                tax: 150.00,
                total: 2650.00,
                orderReceiveRating: 4,
                orderReceiveRemarks: 'Okay',
                orderStatus: 66,
                sap_timestamp: '2025-10-02T13:00:00Z',
                created: '2025-10-02T10:30:00Z'
            },
            {
                id: 6,
                etenUserListID: 'E325632',
                etenUserID: 'EU1006',
                custAccountNo: '6080125300',
                companyName: '',
                salesOrg: '3000',
                distributionChannel: '10',
                division: '01',
                priceGroup: 'PG6',
                sapOrderType: 'OT06',
                customerCondGrp: 'C6',
                shipTo: 'SHIP06',
                shippingCond: '06',
                storageLocation: 'SL06',
                orderDesc: 'OWN',
                channel: 'CARES',
                containerSize: '10FT',
                deliveryType: 'SELFCOLLECT',
                deliveryDate: '2025-10-18',
                eten_user_shiptoID: 'SHP1006',
                orderNo: 'ORD006',
                soNo: 'SO006',
                doNo: 'DO006',
                invNo: 'INV006',
                order_array: ['item10'],
                fullfill_order_array: ['fulfilled10'],
                subtotal: 1800.00,
                tax: 108.00,
                total: 1908.00,
                orderReceiveRating: 2,
                orderReceiveRemarks: 'Need improvement',
                orderStatus: 0, // pending
                sap_timestamp: '2025-10-02T14:00:00Z',
                created: '2025-10-02T11:00:00Z'
            },
            {
                id: 7,
                etenUserListID: 'E346572',
                etenUserID: 'EU1007',
                custAccountNo: '6080100900',
                companyName: '',
                salesOrg: '4000',
                distributionChannel: '20',
                division: '02',
                priceGroup: 'PG7',
                sapOrderType: 'OT07',
                customerCondGrp: 'C7',
                shipTo: 'SHIP07',
                shippingCond: '07',
                storageLocation: 'SL07',
                orderDesc: 'NORMAL',
                channel: 'ETEN',
                containerSize: '20FT',
                deliveryType: 'LALAMOVE',
                deliveryDate: '2025-10-20',
                eten_user_shiptoID: 'SHP1007',
                orderNo: 'ORD007',
                soNo: 'SO007',
                doNo: 'DO007',
                invNo: 'INV007',
                order_array: ['item11','item12'],
                fullfill_order_array: ['fulfilled11'],
                subtotal: 4000.00,
                tax: 240.00,
                total: 4240.00,
                orderReceiveRating: 5,
                orderReceiveRemarks: 'Excellent',
                orderStatus: 77,
                sap_timestamp: '2025-10-02T15:00:00Z',
                created: '2025-10-02T11:30:00Z'
            }
        ];
    },

    getListOrderMini() { 
        return Promise.resolve(this.getListOrderData().slice(0, 5));
    },

    getListOrderSmall() { 
        return Promise.resolve(this.getListOrderData().slice(0, 10));
    },

    getListOrder() { 
        return Promise.resolve(this.getListOrderData());
    },
};
