export const ListGameService = { 
  getListGameData() {
    return [
      {
        id: 1,
        gameNo: "GTY2025001",
        type: "SPIN",
        title: "Toyo Tires Knowledge Challenge",
        desc: "Test your knowledge about Toyo Tires’ history, technology, and innovations. Win exclusive merchandise!",
        imageURL: "https://example.com/images/game-quiz1.jpg",
        image2URL: "https://example.com/images/game-quiz2.jpg",
        image3URL: "https://example.com/images/game-quiz3.jpg",
        termCondition: "Open to all participants in Malaysia. Each user can only attempt once.",
        location: "Online",
        publishDate: "2025-01-10",
        startDate: "2025-01-15",
        endDate: "2025-02-15",
        quota: 1000,
        point1: 80,
        point2: 85,
        point3: 90,
        point4: 95,
        status: 1,
        created: "2025-01-05",
        deleted: null,
      },
      {
        id: 2,
        gameNo: "GTY2025002",
        type: "SPIN",
        title: "Toyo Tires Adventure Capture",
        desc: "Upload your best road trip photo featuring Toyo Tires and stand a chance to win cash vouchers.",
        imageURL: "https://example.com/images/game-photo1.jpg",
        image2URL: "https://example.com/images/game-photo2.jpg",
        image3URL: "https://example.com/images/game-photo3.jpg",
        termCondition: "Photos must include Toyo Tires branding or vehicle with Toyo Tires installed.",
        location: "Online Submission",
        publishDate: "2025-02-01",
        startDate: "2025-02-10",
        endDate: "2025-03-10",
        quota: 500,
        point1: 85,
        point2: 80,
        point3: 88,
        point4: 95,
        status: 1,
        created: "2025-01-30",
        deleted: null,
      },
      {
        id: 3,
        gameNo: "GTY2025003",
        type: "RANDOM",
        title: "Toyo Tires Purchase & Win",
        desc: "Buy any Toyo Tires product and enter the lucky draw for a chance to win exciting prizes.",
        imageURL: "https://example.com/images/game-lucky1.jpg",
        image2URL: "https://example.com/images/game-lucky2.jpg",
        image3URL: "https://example.com/images/game-lucky3.jpg",
        termCondition: "Minimum purchase of 2 Toyo Tires required. Receipt submission is mandatory.",
        location: "Nationwide",
        publishDate: "2025-03-05",
        startDate: "2025-03-10",
        endDate: "2025-04-15",
        quota: 2000,
        point1: 70,
        point2: 75,
        point3: 80,
        point4: 95,
        status: 0,
        created: "2025-03-01",
        deleted: null,
      },
      {
        id: 4,
        gameNo: "GTY2025004",
        type: "SPIN",
        title: "Virtual Drift Challenge with Toyo Tires",
        desc: "Compete in a racing simulator drift challenge to show your skills and win Toyo merchandise.",
        imageURL: "https://example.com/images/game-drift1.jpg",
        image2URL: "https://example.com/images/game-drift2.jpg",
        image3URL: "https://example.com/images/game-drift3.jpg",
        termCondition: "Open to public. Each participant gets 3 attempts per day.",
        location: "Kuala Lumpur Mall Atrium",
        publishDate: "2025-04-01",
        startDate: "2025-04-10",
        endDate: "2025-04-20",
        quota: 300,
        point1: 95,
        point2: 90,
        point3: 85,
        point4: 95,
        status: 1,
        created: "2025-03-28",
        deleted: null,
      },
      {
        id: 5,
        gameNo: "GTY2025005",
        type: "RANDOM",
        title: "Toyo Tires Hashtag Hunt",
        desc: "Join the social media challenge by posting your Toyo Tires experience with #ToyoTiresMY.",
        imageURL: "https://example.com/images/game-hashtag1.jpg",
        image2URL: "https://example.com/images/game-hashtag2.jpg",
        image3URL: "https://example.com/images/game-hashtag3.jpg",
        termCondition: "Entries must be public posts. Multiple submissions allowed.",
        location: "Facebook & Instagram",
        publishDate: "2025-05-05",
        startDate: "2025-05-10",
        endDate: "2025-06-10",
        quota: 1000,
        point1: 75,
        point2: 80,
        point3: 85,
        point4: 95,
        status: "Scheduled",
        created: "2025-05-01",
        deleted: null,
      },
      {
        id: 6,
        gameNo: "GTY2025006",
        type: "RANDOM",
        title: "Toyo Tires Future Mobility Game",
        desc: "A hackathon-style competition where participants design gamified solutions for future tire technologies.",
        imageURL: "https://example.com/images/game-hackathon1.jpg",
        image2URL: "https://example.com/images/game-hackathon2.jpg",
        image3URL: "https://example.com/images/game-hackathon3.jpg",
        termCondition: "Open to university students. Team participation required.",
        location: "Universiti Malaya, Kuala Lumpur",
        publishDate: "2025-06-20",
        startDate: "2025-07-05",
        endDate: "2025-07-07",
        quota: 50,
        point1: 88,
        point2: 92,
        point3: 90,
        point4: 95,
        status: 1,
        created: "2025-06-15",
        deleted: null,
      },
    ];
  },

  getListGameMini() {
    return Promise.resolve(this.getListGameData().slice(0, 5));
  },

  getListGameSmall() {
    return Promise.resolve(this.getListGameData().slice(0, 10));
  },

  getListGame() {
    return Promise.resolve(this.getListGameData());
  },
};
