export const ListTyreService = {
    getListTyreData() {
        return [
            {
                id: 1,
                warrantyRegisterID: 1001,
                materialid: '81114NE0304175H',
                itemdesc: '215/45R17 91W',
                pattern: 'T1R',
                patternName: 'Proxes T1R',
                isTWP: 1,
                sectionWidth: 215,
                tireseries: 45,
                rimDiameter: 17,
                speedplyrating: 'V',
                aspectRatio: '45',
                tyreSize: '215/45R17',
                loadIndex: '91',
                plyRating: 'XL',
                deleted: null,
                status: 'Non-Warranty',
                size: '215/45R17',
                origin: 'Japan',
                desc: 'High-performance tire for sports cars and sedans',
                mfgcode: 'MFG-2025-001',
                tyrespec: '91W',
                weekcode: '3524',
                imageURL: '/demo/images/toyor_tayar1.png'
            },
            {
                id: 2,
                warrantyRegisterID: 1002,
                materialid: '81114NE0304176H',
                itemdesc: '225/45R18 95W',
                pattern: 'TSC',
                patternName: 'Proxes TSC',
                isTWP: 1,
                sectionWidth: 225,
                tireseries: 45,
                rimDiameter: 18,
                speedplyrating: 'W',
                aspectRatio: '45',
                tyreSize: '225/45R18',
                loadIndex: '95',
                plyRating: 'XL',
                deleted: null,
                status: 'Warranty',
                size: '225/45R18',
                origin: 'Thailand',
                desc: 'Comfort-oriented touring tire with long tread life',
                mfgcode: 'MFG-2025-002',
                tyrespec: '95W',
                weekcode: '2724',
                imageURL: '/demo/images/toyor_tayar2.png'
            },
            {
                id: 3,
                warrantyRegisterID: 1003,
                materialid: '81114NE0304177H',
                itemdesc: '195/65R15 91H',
                pattern: 'TR1',
                patternName: 'Proxes TR1',
                isTWP: 1,
                sectionWidth: 195,
                tireseries: 65,
                rimDiameter: 15,
                speedplyrating: 'H',
                aspectRatio: '65',
                tyreSize: '195/65R15',
                loadIndex: '91',
                plyRating: 'SL',
                deleted: null,
                status: 'Non-Warranty',
                size: '195/65R15',
                origin: 'Malaysia',
                desc: 'Reliable all-season performance for compact cars',
                mfgcode: 'MFG-2025-003',
                tyrespec: '91H',
                weekcode: '2924',
                imageURL: '/demo/images/toyor_tayar3.png'
            },
            {
                id: 4,
                warrantyRegisterID: 1004,
                materialid: '81114NE0304178H',
                itemdesc: '245/40R19 98Y',
                pattern: 'TH7',
                patternName: 'Proxes TH7',
                isTWP: 0,
                sectionWidth: 245,
                tireseries: 40,
                rimDiameter: 19,
                speedplyrating: 'Y',
                aspectRatio: '40',
                tyreSize: '245/40R19',
                loadIndex: '98',
                plyRating: 'XL',
                deleted: null,
                status: 'Warranty',
                size: '245/40R19',
                origin: 'Japan',
                desc: 'Ultra-high-performance tire with superior grip',
                mfgcode: 'MFG-2025-004',
                tyrespec: '98Y',
                weekcode: '2424',
                imageURL: '/demo/images/toyor_tayar4.png'
            },
            {
                id: 5,
                warrantyRegisterID: 1005,
                materialid: '81114NE0304179H',
                itemdesc: '185/60R14 82H',
                pattern: 'TEO',
                patternName: 'NanoEnergy TEO',
                isTWP: 1,
                sectionWidth: 185,
                tireseries: 60,
                rimDiameter: 14,
                speedplyrating: 'H',
                aspectRatio: '60',
                tyreSize: '185/60R14',
                loadIndex: '82',
                plyRating: 'SL',
                deleted: null,
                status: 'Non-Warranty',
                size: '185/60R14',
                origin: 'Japan',
                desc: 'Economical tire offering quiet and smooth ride',
                mfgcode: 'MFG-2025-005',
                tyrespec: '82H',
                weekcode: '2224',
                imageURL: '/demo/images/toyor_tayar5.png'
            },
            {
                id: 6,
                warrantyRegisterID: 1006,
                materialid: '81114NE0304180H',
                itemdesc: '205/55R16 91V',
                pattern: 'T35',
                patternName: 'Proxes T35',
                isTWP: 0,
                sectionWidth: 205,
                tireseries: 55,
                rimDiameter: 16,
                speedplyrating: 'V',
                aspectRatio: '55',
                tyreSize: '205/55R16',
                loadIndex: '91',
                plyRating: 'SL',
                deleted: null,
                status: 'Warranty',
                size: '205/55R16',
                origin: 'Indonesia',
                desc: 'Balanced all-round performance for sedans',
                mfgcode: 'MFG-2025-006',
                tyrespec: '91V',
                weekcode: '2524',
                imageURL: '/demo/images/toyor_tayar6.png'
            },
            {
                id: 7,
                warrantyRegisterID: 1007,
                materialid: '81114NE0304181H',
                itemdesc: '215/50R17 95W',
                pattern: 'T1S',
                patternName: 'Proxes T1S',
                isTWP: 1,
                sectionWidth: 215,
                tireseries: 50,
                rimDiameter: 17,
                speedplyrating: 'W',
                aspectRatio: '50',
                tyreSize: '215/50R17',
                loadIndex: '95',
                plyRating: 'XL',
                deleted: null,
                status: 'Non-Warranty',
                size: '215/50R17',
                origin: 'Japan',
                desc: 'Sport tire with improved wet handling and cornering',
                mfgcode: 'MFG-2025-007',
                tyrespec: '95W',
                weekcode: '3324',
                imageURL: '/demo/images/toyor_tayar1.png'
            },
            {
                id: 8,
                warrantyRegisterID: 1008,
                materialid: '81114NE0304182H',
                itemdesc: '235/45R18 98Y',
                pattern: 'C1S',
                patternName: 'Proxes C1S',
                isTWP: 0,
                sectionWidth: 235,
                tireseries: 45,
                rimDiameter: 18,
                speedplyrating: 'Y',
                aspectRatio: '45',
                tyreSize: '235/45R18',
                loadIndex: '98',
                plyRating: 'XL',
                deleted: null,
                status: 'Warranty',
                size: '235/45R18',
                origin: 'Thailand',
                desc: 'Luxury tire for smooth, quiet performance',
                mfgcode: 'MFG-2025-008',
                tyrespec: '98Y',
                weekcode: '3124',
                imageURL: '/demo/images/toyor_tayar3.png'
            },
            {
                id: 9,
                warrantyRegisterID: 1009,
                materialid: '81114NE0304183H',
                itemdesc: '175/65R14 82T',
                pattern: 'Yew',
                patternName: 'Proxes Yew',
                isTWP: 1,
                sectionWidth: 175,
                tireseries: 65,
                rimDiameter: 14,
                speedplyrating: 'T',
                aspectRatio: '65',
                tyreSize: '175/65R14',
                loadIndex: '82',
                plyRating: 'SL',
                deleted: null,
                status: 'Non-Warranty',
                size: '175/65R14',
                origin: 'Vietnam',
                desc: 'Reliable city driving tire with good mileage',
                mfgcode: 'MFG-2025-009',
                tyrespec: '82T',
                weekcode: '2824',
                imageURL: '/demo/images/toyor_tayar4.png'
            }
        ];
    },

    getListTwpTyresData() {
        return [
            { id: 1, materialid: '81114NE0304175H', tyreSize: '215/45R17', pattern: 'Proxes T1R', imageURL: '/demo/images/toyor_tayar1.png' },
            { id: 2, materialid: '81114NE0304176H', tyreSize: '265/65R18', pattern: 'Open Country A/T III', imageURL: '/demo/images/toyor_tayar2.png' },
            { id: 3, materialid: '81114NE0304177H', tyreSize: '245/40R19', pattern: 'Proxes Sport', imageURL: '/demo/images/toyor_tayar3.png' },
            { id: 4, materialid: '81114NE0304179H', tyreSize: '285/70R17', pattern: 'Open Country M/T', imageURL: '/demo/images/toyor_tayar5.png' }
        ];
    },

    getListTyreMini() {
        return Promise.resolve(this.getListTyreData().slice(0, 5));
    },

    getListTyreSmall() {
        return Promise.resolve(this.getListTyreData().slice(0, 10));
    },

    getListTyre() {
        return Promise.resolve(this.getListTyreData());
    },

    getListTwpTyres() {
        return Promise.resolve(this.getListTwpTyresData());
    }
};
