// ListRedeem.js

export const ListRedeemService = {
  getListRedeemData() {
    return [
      {
        id: 1,
        refno: 'TYO-MY-1001',
        tc_userID: 'U1001',
        memberLevel: 'Gold',
        recipientName: 'Ahmad Faizal',
        contactNumber: '012-3456789',
        addLine1: 'No. 12, Jalan Melur',
        addLine2: 'Taman Melawati',
        addCity: 'Kuala Lumpur',
        addState: 'Selangor',
        addPostcode: '53100',
        addCountry: 'Malaysia',
        totalPoint: 500,
        courierName: 'DHL Express',
        trackingNumber: 'DHLMY10001',
        shippedDate: '2024-04-01',
        status: 'Shipped',
        adminID: 'admin01',
        approvedBy: 'admin01',
        verifiedDate: '2024-04-02',
        created: '2024-03-25',
        deleted: false,
      },
      {
        id: 2,
        refno: 'TYO-MY-1002',
        tc_userID: 'U1002',
        memberLevel: 'Silver',
        recipientName: 'Siti Aisyah',
        contactNumber: '013-9876543',
        addLine1: 'No. 45, Jalan Kenanga',
        addLine2: 'Taman Melati',
        addCity: 'Kuala Lumpur',
        addState: 'Selangor',
        addPostcode: '50300',
        addCountry: 'Malaysia',
        totalPoint: 300,
        courierName: 'FedEx Malaysia',
        trackingNumber: 'FEDEXMY2002',
        shippedDate: '2024-04-03',
        status: 'Shipped',
        adminID: 'admin02',
        approvedBy: 'admin02',
        verifiedDate: '2024-04-04',
        created: '2024-03-26',
        deleted: false,
      },
      {
        id: 3,
        refno: 'TYO-MY-1003',
        tc_userID: 'U1003',
        memberLevel: 'Platinum',
        recipientName: 'Lee Tan',
        contactNumber: '014-1234567',
        addLine1: 'No. 78, Jalan Bukit Bintang',
        addLine2: 'Bukit Bintang',
        addCity: 'Kuala Lumpur',
        addState: 'Wilayah Persekutuan',
        addPostcode: '55100',
        addCountry: 'Malaysia',
        totalPoint: 700,
        courierName: 'DHL Express',
        trackingNumber: 'DHLMY10003',
        shippedDate: '2024-04-05',
        status: 'Shipped',
        adminID: 'admin03',
        approvedBy: 'admin03',
        verifiedDate: '2024-04-06',
        created: '2024-03-27',
        deleted: false,
      },
      {
        id: 4,
        refno: 'TYO-MY-1004',
        tc_userID: 'U1004',
        memberLevel: 'Gold',
        recipientName: 'Nurul Izzah',
        contactNumber: '011-2345678',
        addLine1: 'No. 23, Jalan Riong',
        addLine2: 'Bangsar',
        addCity: 'Kuala Lumpur',
        addState: 'Wilayah Persekutuan',
        addPostcode: '59100',
        addCountry: 'Malaysia',
        totalPoint: 450,
        courierName: 'Pos Laju',
        trackingNumber: 'POSMY1004',
        shippedDate: '2024-04-07',
        status: 'Shipped',
        adminID: 'admin04',
        approvedBy: 'admin04',
        verifiedDate: '2024-04-08',
        created: '2024-03-28',
        deleted: false,
      },
      {
        id: 5,
        refno: 'TYO-MY-1005',
        tc_userID: 'U1005',
        memberLevel: 'Silver',
        recipientName: 'Mohamad Rizal',
        contactNumber: '012-9876543',
        addLine1: 'No. 56, Jalan Tuanku Abdul Rahman',
        addLine2: 'Medan Tuanku',
        addCity: 'Kuala Lumpur',
        addState: 'Wilayah Persekutuan',
        addPostcode: '50350',
        addCountry: 'Malaysia',
        totalPoint: 250,
        courierName: 'DHL Express',
        trackingNumber: 'DHLMY10005',
        shippedDate: '2024-04-09',
        status: 'Shipped',
        adminID: 'admin05',
        approvedBy: 'admin05',
        verifiedDate: '2024-04-10',
        created: '2024-03-29',
        deleted: false,
      },
      {
        id: 6,
        refno: 'TYO-MY-1006',
        tc_userID: 'U1006',
        memberLevel: 'Gold',
        recipientName: 'Chong Wei',
        contactNumber: '013-5556666',
        addLine1: 'No. 89, Jalan Sultan Ismail',
        addLine2: 'Bukit Bintang',
        addCity: 'Kuala Lumpur',
        addState: 'Wilayah Persekutuan',
        addPostcode: '50250',
        addCountry: 'Malaysia',
        totalPoint: 600,
        courierName: 'FedEx Malaysia',
        trackingNumber: 'FEDEXMY1006',
        shippedDate: '2024-04-11',
        status: 'Shipped',
        adminID: 'admin06',
        approvedBy: 'admin06',
        verifiedDate: '2024-04-12',
        created: '2024-03-30',
        deleted: false,
      },
      {
        id: 7,
        refno: 'TYO-MY-1007',
        tc_userID: 'U1007',
        memberLevel: 'Platinum',
        recipientName: 'Liyana Azman',
        contactNumber: '014-7778888',
        addLine1: 'No. 34, Jalan Ampang',
        addLine2: 'Ampang',
        addCity: 'Kuala Lumpur',
        addState: 'Wilayah Persekutuan',
        addPostcode: '50450',
        addCountry: 'Malaysia',
        totalPoint: 800,
        courierName: 'DHL Express',
        trackingNumber: 'DHLMY1007',
        shippedDate: '2024-04-13',
        status: 'Shipped',
        adminID: 'admin07',
        approvedBy: 'admin07',
        verifiedDate: '2024-04-14',
        created: '2024-03-31',
        deleted: false,
      },
      {
        id: 8,
        refno: 'TYO-MY-1008',
        tc_userID: 'U1008',
        memberLevel: 'Silver',
        recipientName: 'Ravi Kumar',
        contactNumber: '017-1234567',
        addLine1: 'No. 78, Jalan Pahang',
        addLine2: 'Setapak',
        addCity: 'Kuala Lumpur',
        addState: 'Wilayah Persekutuan',
        addPostcode: '53000',
        addCountry: 'Malaysia',
        totalPoint: 350,
        courierName: 'Pos Laju',
        trackingNumber: 'POSMY1008',
        shippedDate: '2024-04-15',
        status: 'Shipped',
        adminID: 'admin08',
        approvedBy: 'admin08',
        verifiedDate: '2024-04-16',
        created: '2024-04-01',
        deleted: false,
      },
      {
        id: 9,
        refno: 'TYO-MY-1009',
        tc_userID: 'U1009',
        memberLevel: 'Gold',
        recipientName: 'Nurul Huda',
        contactNumber: '018-2223333',
        addLine1: 'No. 22, Jalan Tunku Abdul Rahman',
        addLine2: 'Kampung Baru',
        addCity: 'Kuala Lumpur',
        addState: 'Wilayah Persekutuan',
        addPostcode: '50350',
        addCountry: 'Malaysia',
        totalPoint: 520,
        courierName: 'DHL Express',
        trackingNumber: 'DHLMY1009',
        shippedDate: '2024-04-17',
        status: 'Shipped',
        adminID: 'admin09',
        approvedBy: 'admin09',
        verifiedDate: '2024-04-18',
        created: '2024-04-02',
        deleted: false,
      },
      {
        id: 10,
        refno: 'TYO-MY-1010',
        tc_userID: 'U1010',
        memberLevel: 'Silver',
        recipientName: 'Mohd Azmi',
        contactNumber: '019-4445555',
        addLine1: 'No. 90, Jalan Kuching',
        addLine2: 'Miri',
        addCity: 'Miri',
        addState: 'Sarawak',
        addPostcode: '98000',
        addCountry: 'Malaysia',
        totalPoint: 280,
        courierName: 'Pos Laju',
        trackingNumber: 'POSMY1010',
        shippedDate: '2024-04-19',
        status: 'Shipped',
        adminID: 'admin10',
        approvedBy: 'admin10',
        verifiedDate: '2024-04-20',
        created: '2024-04-03',
        deleted: false,
      },
    ];
  },

  getListRedeemMini() {
    return Promise.resolve(this.getListRedeemData().slice(0, 5));
  },

  getListRedeemSmall() {
    return Promise.resolve(this.getListRedeemData().slice(0, 10));
  },

  getListRedeem() {
    return Promise.resolve(this.getListRedeemData());
  },
};