export const ListLogisticService = { 
  getListLogisticData() { 
    return [
      {
        companyName: "JNT",
        orderNo: 'ORD001',
        accountNo: '6080100900',
        contactPerson: "John Doe",
        contactNo: "123-456-7890",
        address: "Toyo Tires Malaysia, Jalan Toyo, Off Jalan Klang Lama",
        city: "Shah Alam",
        postcode: "47301",
        state: "Selangor",
        email: "contact@jntlogistics.com",
        username: "jnt_user01",
        password: "password123",
        status: "1",
        shippingPoints: ["JNT"],
        storageLocation: "TMJB",
        createdSince: "2023-01-15T09:30:00",
        lastLogin: "2023-10-01T14:45:00"
      },
      {
        companyName: "Ninja Van",
        orderNo: 'ORD002',
        accountNo: '6080102300',
        contactPerson: "Jane Smith",
        contactNo: "987-654-3210",
        address: "Toyo Tires Malaysia, Lot 123, Jalan Toyo, Shah Alam",
        city: "Shah Alam",
        postcode: "47301",
        state: "Selangor",
        email: "jane.smith@ninjavan.com",
        username: "ninjavan_user01",
        password: "securepass456",
        status: "1",
        shippingPoints: ["Ninja Van"],
        storageLocation: "TMSA",
        createdSince: "2022-11-20T11:00:00",
        lastLogin: "2023-09-25T10:15:00"
      },
      {
        companyName: "Lalamove",
        orderNo: 'ORD003',
        accountNo: '6080102301',
        contactPerson: "Alex Tan",
        contactNo: "555-123-4567",
        address: "Toyo Tires Malaysia, 45, Jalan Toyo, Shah Alam",
        city: "Shah Alam",
        postcode: "47301",
        state: "Selangor",
        email: "alex.tan@lalamove.com",
        username: "lalamove_user01",
        password: "lalamove789",
        status: "0",
        shippingPoints: ["Lalamove"],
        storageLocation: "RETP",
        createdSince: "2023-03-10T08:45:00",
        lastLogin: "2023-08-30T16:20:00"
      },
      {
        companyName: "Flash",
        orderNo: 'ORD004',
        accountNo: '6080102302',
        contactPerson: "Sara Lee",
        contactNo: "321-654-9870",
        address: "Toyo Tires Malaysia, 78, Jalan Toyo, Shah Alam",
        city: "Shah Alam",
        postcode: "47301",
        state: "Selangor",
        email: "sara.lee@flash.com",
        username: "flash_user01",
        password: "flashpass321", 
        status: "1",
        shippingPoints: ["JNT", "Lalamove"],
        storageLocation: "TMSB",
        createdSince: "2022-06-05T14:00:00",
        lastLogin: "2023-09-20T09:30:00"
      },
      {
        companyName: "JNT",
        orderNo: 'ORD005',
         accountNo: '6080114400',
        contactPerson: "Michael Chong",
        contactNo: "666-777-8888",
        address: "Toyo Tires Malaysia, 100, Jalan Toyo, Shah Alam",
        city: "Shah Alam",
        postcode: "47301",
        state: "Selangor",
        email: "michael.chong@expressway.com",
        username: "expressway_user",
        password: "express123",
        status: "1",
        shippingPoints: ["DHL"],
        storageLocation: "TMSK",
        createdSince: "2021-12-01T10:15:00",
        lastLogin: "2023-09-28T17:10:00"
      },
      {
        companyName: "Ninja Van",
        orderNo: 'ORD006',
         accountNo: '6080125300',
        contactPerson: "Nina Patel",
        contactNo: "222-333-4444",
        address: "Toyo Tires Malaysia, 56, Jalan Toyo, Shah Alam",
        city: "Shah Alam",
        postcode: "47301",
        state: "Selangor",
        email: "nina.patel@speedydelivery.com",
        username: "speedy_user",
        password: "speedy456",
        status: "0",
        shippingPoints: ["JNT"],
        storageLocation: "TMJB",
        createdSince: "2020-08-10T13:45:00",
        lastLogin: "2022-12-15T12:00:00"
      },
      {
        companyName: "Lalamove",
        orderNo: 'ORD007',
         accountNo: '6080102301',
        contactPerson: "Tom Nguyen",
        contactNo: "777-888-9999",
        address: "Toyo Tires Malaysia, 89, Jalan Toyo, Shah Alam",
        city: "Shah Alam",
        postcode: "47301",
        state: "Selangor",
        email: "tom.nguyen@globalship.com",
        username: "globalship_user",
        password: "global789",
        status: "1",
        shippingPoints: ["Lalamove"],
        storageLocation: "RER",
        createdSince: "2022-03-22T09:00:00",
        lastLogin: "2023-10-02T11:45:00"
      },
      {
        companyName: "Flash",
        orderNo: 'ORD008',
         accountNo: '6080102302',
        contactPerson: "Emma Watson",
        contactNo: "888-222-3333",
        address: "Toyo Tires Malaysia, 101, Jalan Toyo, Shah Alam",
        city: "Shah Alam",
        postcode: "47301",
        state: "Selangor",
        email: "emma.watson@nextday.com",
        username: "nextday_user",
        password: "nextday321", 
        status: "1",
        shippingPoints: ["DHL", "Lalamove"],
        storageLocation: "TMSB",
        createdSince: "2021-05-15T16:30:00",
        lastLogin: "2023-09-30T15:20:00"
      },
      {
        companyName: "Ninja Van",
        orderNo: 'ORD009',
         accountNo: '6080102302',
        contactPerson: "Carlos Mendez",
        contactNo: "444-555-6666",
        address: "Toyo Tires Malaysia, 102, Jalan Toyo, Shah Alam",
        city: "Shah Alam",
        postcode: "47301",
        state: "Selangor",
        email: "carlos.mendez@expressfast.com",
        username: "expressfast_user",
        password: "expressfast654",
        status: "0",
        shippingPoints: ["JNT"],
        storageLocation: "TMSA",
        createdSince: "2020-05-01T08:00:00",
        lastLogin: "2022-10-10T09:00:00"
      }
    ];
  },

  getListOrderMini() { 
    return Promise.resolve(this.getListLogisticData().slice(0, 5));
  },

  getListOrderSmall() { 
    return Promise.resolve(this.getListLogisticData().slice(0, 10));
  },

  getListOrder() { 
    return Promise.resolve(this.getListLogisticData());
  },
};