export const ListNewsService = { 
  getListNewsData() {
    return [
      {
        id: 1,
        audience: "TC",
        title: "Toyo Tires Launches Proxes Sport 2 in Malaysia",
        image1URL: "https://example.com/images/proxes1.jpg",
        image2URL: "https://example.com/images/proxes2.jpg",
        image3URL: "https://example.com/images/proxes3.jpg",
        desc: "Toyo Tires introduces its latest high-performance tire, Proxes Sport 2, designed for superior handling and grip on Malaysian roads.",
        location: "Kuala Lumpur, Malaysia",
        publishDate: "2025-01-12",
        startDate: "2025-01-15",
        endDate: "2025-02-15",
        status: 1,
        created: "2025-01-10",
        deleted: null,
        view: 1500,
      },
      {
        id: 2,
        audience: "ETEN",
        title: "Toyo Tires Sponsors Sepang Drift Championship 2025",
        image1URL: "https://example.com/images/drift1.jpg",
        image2URL: "https://example.com/images/drift2.jpg",
        image3URL: "https://example.com/images/drift3.jpg",
        desc: "The Sepang Drift Championship returns with Toyo Tires as the official tire sponsor, bringing adrenaline-packed action for motorsport fans.",
        location: "Sepang International Circuit",
        publishDate: null,
        startDate: "2025-02-20",
        endDate: "2025-02-21",
        status: 2,
        created: "2025-02-01",
        deleted: null,
        view: 300,
      },
      {
        id: 3,
        audience: "ALL",
        title: "Toyo Tires Expands Dealer Network in Johor",
        image1URL: "https://example.com/images/dealer1.jpg",
        image2URL: "https://example.com/images/dealer2.jpg",
        image3URL: "https://example.com/images/dealer3.jpg",
        desc: "Toyo Tires strengthens its presence in Southern Malaysia by expanding its dealer network, ensuring better accessibility for customers.",
        location: "Johor Bahru, Malaysia",
        publishDate: null,
        startDate: "2025-03-15",
        endDate: "2025-04-15",
        status: 0,
        created: "2025-03-10",
        deleted: null,
        view: 700,
      },
      {
        id: 4,
        audience: "TC",
        title: "Toyo Tires Green Mobility Initiative Launched",
        image1URL: "https://example.com/images/green1.jpg",
        image2URL: "https://example.com/images/green2.jpg",
        image3URL: "https://example.com/images/green3.jpg",
        desc: "Toyo Tires unveils its eco-friendly tire technology as part of its global commitment to sustainable mobility solutions.",
        location: "Penang, Malaysia",
        publishDate: null,
        startDate: "2025-04-22",
        endDate: "2025-05-22",
        status: 0,
        created: "2025-04-18",
        deleted: null,
        view: 1000,
      },
      {
        id: 5,
        audience: "TC",
        title: "Toyo Tires Announces Off-Road Rally Malaysia 2025",
        image1URL: "https://example.com/images/offroad1.jpg",
        image2URL: "https://example.com/images/offroad2.jpg",
        image3URL: "https://example.com/images/offroad3.jpg",
        desc: "An exciting off-road rally powered by Toyo Tires will challenge participants through rugged terrains in Johor’s tropical forests.",
        location: "Johor Bahru, Malaysia",
        publishDate: "2025-05-30",
        startDate: "2025-06-10",
        endDate: "2025-06-12",
        status: 1,
        created: "2025-05-25",
        deleted: null,
        view: 2000,
      },
      {
        id: 6,
        audience: "TC",
        title: "Toyo Tires Partners with Universiti Malaya for Innovation Hackathon",
        image1URL: "https://example.com/images/hackathon1.jpg",
        image2URL: "https://example.com/images/hackathon2.jpg",
        image3URL: "https://example.com/images/hackathon3.jpg",
        desc: "Toyo Tires collaborates with Universiti Malaya to host a hackathon, encouraging young innovators to create smart mobility solutions.",
        location: "Kuala Lumpur, Malaysia",
        publishDate: "2025-07-08",
        startDate: "2025-07-25",
        endDate: "2025-07-27",
        status: 1,
        created: "2025-07-01",
        deleted: null,
        view: 1200,
      },
    ];
  },

  getListNewsMini() {
    return Promise.resolve(this.getListNewsData().slice(0, 5));
  },

  getListNewsSmall() {
    return Promise.resolve(this.getListNewsData().slice(0, 10));
  },

  getListNews() {
    return Promise.resolve(this.getListNewsData());
  },
};