export const ListReturnOrderService = {
    getListReturnOrderData() {
        return [
            {
                id: 1,
                returnRequestNo: 'RR1001',
                orderNo: 'TYO1001',
                soNo: 'SO1001',
                doNo: 'DO1001',
                invoiceNo: 'INV1001',
                returnMaterial: 'TYRE-R15-001',
                returnReason: 'Defective tyre - air leakage',
                reasonCode: 'R001',
                reasonMessage: 'Product defective - air leakage detected',
                quantity: 4,
                total: 1200.0,
                etenUserListID: 'U12345',
                etenUserID: 'U67890',
                custAccountNo: '6080100900',
                customerName: 'PS Tyres & Battery Auto Services Sdn. Bhd',
                location: '123 Toyo Road, Toyo Industrial Park, 50000 Kuala Lumpur, Malaysia',
                signboard: 'T10',
                salesOrg: 'SO001',
                distributionChannel: 'ETEN',
                division: 'DIV01',
                priceGroup: 'PG01',
                sapOrderType: 'NORMAL',
                customerCondGrp: 'CCG1',
                shipTo: 'YESSIR TYRES SOLUTION SDN BHD',
                shippingCond: 'Standard',
                storageLocation: 'LOC01',
                orderDesc: 'Order for electronics',
                channel: 'ETEN',
                deliveryType: 'DELIVER',
                deliveryDate: '2023-10-15',
                boOrderNo: 'BO1001',
                backOrderArray: [],
                fulfillArray: [],
                orderStatus: 3, // Completed
                expiry: '2023-11-15',
                created: '2023-10-01',
                modified: '2023-10-05'
            },
            {
                id: 2,
                returnRequestNo: 'RR1002',
                orderNo: 'TYO1002',
                soNo: 'SO1002',
                doNo: 'DO1002',
                invoiceNo: 'INV1002',
                returnMaterial: 'TYRE-R17-002',
                returnReason: 'Wrong size delivered',
                reasonCode: 'R002',
                reasonMessage: 'Delivered tyre size does not match order',
                quantity: 2,
                total: 800.0,
                etenUserListID: 'U23456',
                etenUserID: 'U78901',
                custAccountNo: '6080102300',
                customerName: 'Toyo Auto Centre UHP Tyres Sdn Bhd',
                location: '456 Auto Lane, Auto City, 60000 Petaling Jaya, Malaysia',
                signboard: 'TTC',
                salesOrg: 'SO002',
                distributionChannel: 'ADMIN',
                division: 'DIV02',
                priceGroup: 'PG02',
                sapOrderType: 'DIRECTSHIP',
                customerCondGrp: 'CCG2',
                shipTo: 'WING HING TYRE SERVICE SDN BHD',
                shippingCond: 'Express',
                storageLocation: 'LOC02',
                orderDesc: 'Order for furniture',
                channel: 'ADMIN',
                deliveryType: 'SELFCOLLECT',
                deliveryDate: '2023-10-20',
                boOrderNo: 'BO1002',
                backOrderArray: [],
                fulfillArray: [],
                orderStatus: 0, // Pending Approval
                expiry: '2023-11-20',
                created: '2023-10-02',
                modified: '2023-10-06'
            },
            {
                id: 3,
                returnRequestNo: 'RR1003',
                orderNo: 'TYO1003',
                soNo: 'SO1003',
                doNo: 'DO1003',
                invoiceNo: 'INV1003',
                returnMaterial: 'TYRE-R18-003',
                returnReason: 'Customer cancelled order',
                reasonCode: 'R003',
                reasonMessage: 'Customer requested order cancellation',
                quantity: 1,
                total: 450.0,
                etenUserListID: 'U34567',
                etenUserID: 'U89012',
                custAccountNo: '6080102301',
                customerName: 'Tek Ming Auto Service Sdn. Bhd.',
                location: '789 Service Street, Service Town, 70000 Seremban, Malaysia',
                signboard: 'TPC',
                salesOrg: 'SO003',
                division: 'DIV03',
                priceGroup: 'PG03',
                sapOrderType: 'OWN',
                customerCondGrp: 'CCG3',
                shipTo: 'TYREPLUS - SHAH ALAM TYRES & AUTO ACCESSORIES',
                shippingCond: 'Lalamove',
                storageLocation: 'LOC03',
                orderDesc: 'Order for books',
                channel: 'CARES',
                deliveryType: 'LALAMOVE',
                deliveryDate: '2023-10-25',
                boOrderNo: 'BO1003',
                backOrderArray: [],
                fulfillArray: [],
                orderStatus: 2, // Processing
                expiry: '2023-11-25',
                created: '2023-10-03',
                modified: '2023-10-07'
            },
            {
                id: 4,
                returnRequestNo: 'RR1004',
                orderNo: 'TYO1004',
                soNo: 'SO1004',
                doNo: 'DO1004',
                invoiceNo: 'INV1004',
                returnMaterial: 'TYRE-R16-004',
                returnReason: 'Damaged during transport',
                reasonCode: 'R004',
                reasonMessage: 'Tyre arrived damaged in transit',
                quantity: 3,
                total: 1050.0,
                etenUserListID: 'U45678',
                etenUserID: 'U90123',
                custAccountNo: '6080102302',
                customerName: 'Apex Tyre & Car Care',
                location: '321 Care Avenue, Care City, 80000 Johor Bahru, Malaysia',
                signboard: 'TST',
                salesOrg: 'SO004',
                division: 'DIV04',
                priceGroup: 'PG04',
                sapOrderType: 'NORMAL',
                customerCondGrp: 'CCG4',
                shipTo: 'WING HING TYRE SERVICE SDN BHD',
                shippingCond: 'Standard',
                storageLocation: 'LOC04',
                orderDesc: 'Order for appliances',
                channel: 'ETEN',
                deliveryType: 'DELIVER',
                deliveryDate: '2023-10-18',
                boOrderNo: 'BO1004',
                backOrderArray: [],
                fulfillArray: [],
                orderStatus: 3, // Completed
                expiry: '2023-11-18',
                created: '2023-10-04',
                modified: '2023-10-08'
            },
            {
                id: 5,
                returnRequestNo: 'RR1005',
                orderNo: 'TYO1005',
                soNo: 'SO1005',
                doNo: 'DO1005',
                invoiceNo: 'INV1005',
                returnMaterial: 'TYRE-R14-005',
                returnReason: 'Expired stock returned',
                reasonCode: 'R005',
                reasonMessage: 'Tyre returned due to expiration',
                quantity: 5,
                total: 1500.0,
                etenUserListID: 'U56789',
                etenUserID: 'U01234',
                custAccountNo: '6080102303',
                customerName: 'Elite Tyre Workshop',
                location: '12 Elite Street, Klang, 41000 Selangor, Malaysia',
                signboard: 'ETW',
                salesOrg: 'SO005',
                division: 'DIV05',
                priceGroup: 'PG05',
                sapOrderType: 'NORMAL',
                customerCondGrp: 'CCG5',
                shipTo: 'TOYO AUTO SERVICE CENTRE',
                shippingCond: 'Standard',
                storageLocation: 'LOC05',
                orderDesc: 'Order for vehicle parts',
                channel: 'ETEN',
                deliveryType: 'DELIVER',
                deliveryDate: '2023-10-26',
                boOrderNo: 'BO1005',
                backOrderArray: [],
                fulfillArray: [],
                orderStatus: 1, // Approved
                expiry: '2023-11-26',
                created: '2023-10-05',
                modified: '2023-10-09'
            },
            {
                id: 6,
                returnRequestNo: 'RR1006',
                orderNo: 'TYO1006',
                soNo: 'SO1006',
                doNo: 'DO1006',
                invoiceNo: 'INV1006',
                returnMaterial: 'TYRE-R19-006',
                returnReason: 'Incorrect invoice details',
                reasonCode: 'R006',
                reasonMessage: 'Invoice contained incorrect customer information',
                quantity: 2,
                total: 900.0,
                etenUserListID: 'U67890',
                etenUserID: 'U12345',
                custAccountNo: '6080102304',
                customerName: 'CarPro Tyre & Auto',
                location: '88 Jalan Ampang, 50450 Kuala Lumpur, Malaysia',
                signboard: 'CPT',
                salesOrg: 'SO006',
                division: 'DIV06',
                priceGroup: 'PG06',
                sapOrderType: 'OWN',
                customerCondGrp: 'CCG6',
                shipTo: 'ETEN AUTO SOLUTIONS',
                shippingCond: 'Express',
                storageLocation: 'LOC06',
                orderDesc: 'Order for maintenance items',
                channel: 'ADMIN',
                deliveryType: 'SELFCOLLECT',
                deliveryDate: '2023-10-28',
                boOrderNo: 'BO1006',
                backOrderArray: [],
                fulfillArray: [],
                orderStatus: 2, // Processing
                expiry: '2023-11-28',
                created: '2023-10-06',
                modified: '2023-10-10'
            },
            {
                id: 7,
                returnRequestNo: 'RR1007',
                orderNo: 'TYO1007',
                soNo: 'SO1007',
                doNo: 'DO1007',
                invoiceNo: 'INV1007',
                returnMaterial: 'TYRE-R20-007',
                returnReason: 'Tyre sidewall damage',
                reasonCode: 'R007',
                reasonMessage: 'Visible damage on tyre sidewall upon delivery',
                quantity: 1,
                total: 480.0,
                etenUserListID: 'U78901',
                etenUserID: 'U23456',
                custAccountNo: '6080102305',
                customerName: 'Max Performance Tyres',
                location: '22 Jalan Tun Razak, 50400 Kuala Lumpur, Malaysia',
                signboard: 'MPT',
                salesOrg: 'SO007',
                division: 'DIV07',
                priceGroup: 'PG07',
                sapOrderType: 'DIRECTSHIP',
                customerCondGrp: 'CCG7',
                shipTo: 'YESSIR TYRES SOLUTION SDN BHD',
                shippingCond: 'Standard',
                storageLocation: 'LOC07',
                orderDesc: 'Order for racing tyres',
                channel: 'CARES',
                deliveryType: 'DELIVER',
                deliveryDate: '2023-10-30',
                boOrderNo: 'BO1007',
                backOrderArray: [],
                fulfillArray: [],
                orderStatus: 3, // Completed
                expiry: '2023-11-30',
                created: '2023-10-07',
                modified: '2023-10-11'
            },
            {
                id: 8,
                returnRequestNo: 'RR1008',
                orderNo: 'TYO1008',
                soNo: 'SO1008',
                doNo: 'DO1008',
                invoiceNo: 'INV1008',
                returnMaterial: 'TYRE-R17-008',
                returnReason: 'Excess stock returned',
                reasonCode: 'R008',
                reasonMessage: 'Surplus stock returned from distributor',
                quantity: 3,
                total: 1100.0,
                etenUserListID: 'U89012',
                etenUserID: 'U34567',
                custAccountNo: '6080102306',
                customerName: 'Auto Empire Garage',
                location: '77 Jalan Kuchai Lama, 58200 Kuala Lumpur, Malaysia',
                signboard: 'AEG',
                salesOrg: 'SO008',
                division: 'DIV08',
                priceGroup: 'PG08',
                sapOrderType: 'NORMAL',
                customerCondGrp: 'CCG8',
                shipTo: 'AUTOCARE SERVICE STATION',
                shippingCond: 'Standard',
                storageLocation: 'LOC08',
                orderDesc: 'Order for accessories',
                channel: 'ETEN',
                deliveryType: 'DELIVER',
                deliveryDate: '2023-11-01',
                boOrderNo: 'BO1008',
                backOrderArray: [],
                fulfillArray: [],
                orderStatus: 1, // Approved
                expiry: '2023-12-01',
                created: '2023-10-08',
                modified: '2023-10-12'
            },
            {
                id: 9,
                returnRequestNo: 'RR1009',
                orderNo: 'TYO1009',
                soNo: 'SO1009',
                doNo: 'DO1009',
                invoiceNo: 'INV1009',
                returnMaterial: 'TYRE-R16-009',
                returnReason: 'Wrong label printed',
                reasonCode: 'R009',
                reasonMessage: 'Incorrect label information on tyre batch',
                quantity: 6,
                total: 1650.0,
                etenUserListID: 'U90123',
                etenUserID: 'U45678',
                custAccountNo: '6080102307',
                customerName: 'Speedy Wheels Centre',
                location: '18 Jalan Gombak, 53000 Kuala Lumpur, Malaysia',
                signboard: 'SWC',
                salesOrg: 'SO009',
                division: 'DIV09',
                priceGroup: 'PG09',
                sapOrderType: 'OWN',
                customerCondGrp: 'CCG9',
                shipTo: 'TOYO AUTO WORKSHOP',
                shippingCond: 'Express',
                storageLocation: 'LOC09',
                orderDesc: 'Order for tools',
                channel: 'ADMIN',
                deliveryType: 'SELFCOLLECT',
                deliveryDate: '2023-11-05',
                boOrderNo: 'BO1009',
                backOrderArray: [],
                fulfillArray: [],
                orderStatus: 0, // Pending Approval
                expiry: '2023-12-05',
                created: '2023-10-09',
                modified: '2023-10-13'
            },
            {
                id: 10,
                returnRequestNo: 'RR1010',
                orderNo: 'TYO1010',
                soNo: 'SO1010',
                doNo: 'DO1010',
                invoiceNo: 'INV1010',
                returnMaterial: 'TYRE-R21-010',
                returnReason: 'Customer changed mind',
                reasonCode: 'R010',
                reasonMessage: 'Customer declined order after confirmation',
                quantity: 2,
                total: 950.0,
                etenUserListID: 'U01234',
                etenUserID: 'U56789',
                custAccountNo: '6080102308',
                customerName: 'GT Tyres & Auto',
                location: '9 Jalan Tebrau, 80300 Johor Bahru, Malaysia',
                signboard: 'GTT',
                salesOrg: 'SO010',
                division: 'DIV10',
                priceGroup: 'PG10',
                sapOrderType: 'DIRECTSHIP',
                customerCondGrp: 'CCG10',
                shipTo: 'AUTOHUB TYRE STATION',
                shippingCond: 'Lalamove',
                storageLocation: 'LOC10',
                orderDesc: 'Order for electronics',
                channel: 'CARES',
                deliveryType: 'LALAMOVE',
                deliveryDate: '2023-11-10',
                boOrderNo: 'BO1010',
                backOrderArray: [],
                fulfillArray: [],
                orderStatus: 2, // Processing
                expiry: '2023-12-10',
                created: '2023-10-10',
                modified: '2023-10-14'
            }
        ];
    },

    getListReturnOrderMini() {
        return Promise.resolve(this.getListReturnOrderData().slice(0, 5));
    },

    getListReturnOrderSmall() {
        return Promise.resolve(this.getListReturnOrderData().slice(0, 10));
    },

    getListReturnOrder() {
        return Promise.resolve(this.getListReturnOrderData());
    }
};
