export const ListEtenUserService = {
  getListEtenUserData() {
    return [
      {
        id: 1,
        etenUserID: 'EU1001',
        countryCode: '60',
        mobileNumber: '1234567890',
        password: 'hashed_pw_1',
        firstName: 'Hafiz',
        lastName: 'Din',
        emailAddress: 'hafiz.din@toyotires.com.my',
        gender: 'Male',
        race: 'Malay',
        state: 'Selangor',
        level: 'Platinum',
        memberSince: '2025-01-01',
        lastLogin: '2025-09-20 10:30:00',
        allow_warranty: 1,
        allow_order: 1,
        allow_billing: 1,
        allow_sale: 1,
        allow_user: 1,
        activationCode: 'ACT12345',
        isMaster: 1,
        device: 'iPhone 14',
        platform: 'iOS',
        fcmToken: 'fcm_token_1',
        status: 1,
        activated: 1,
        created: '2025-01-01',
        deleted: 0
      },
      {
        id: 2,
        etenUserID: 'EU1002',
        countryCode: '60',
        mobileNumber: '1987654321',
        password: 'hashed_pw_2',
        firstName: 'Ahmad',
        lastName: 'Shah',
        emailAddress: 'ahmad.shah@toyotires.com.my',
        gender: 'Male',
        race: 'Malay',
        state: 'Johor',
        level: 'Gold',
        memberSince: '2025-01-15',
        lastLogin: '2025-09-18 14:20:00',
        allow_warranty: 1,
        allow_order: 1,
        allow_billing: 0,
        allow_sale: 1,
        allow_user: 0,
        activationCode: 'ACT23456',
        isMaster: 0,
        device: 'Samsung Galaxy S23',
        platform: 'Android',
        fcmToken: 'fcm_token_2',
        status: 1,
        activated: 1,
        created: '2025-01-15',
        deleted: 0
      },
      {
        id: 3,
        etenUserID: 'EU1003',
        countryCode: '60',
        mobileNumber: '1122334455',
        password: 'hashed_pw_3',
        firstName: 'Farah',
        lastName: 'Ali',
        emailAddress: 'farah.ali@toyotires.com.my',
        gender: 'Female',
        race: 'Malay',
        state: 'Penang',
        level: 'Silver',
        memberSince: '2025-02-01',
        lastLogin: '2025-09-15 09:10:00',
        allow_warranty: 0,
        allow_order: 1,
        allow_billing: 1,
        allow_sale: 0,
        allow_user: 0,
        activationCode: 'ACT34567',
        isMaster: 0,
        device: 'Huawei P60',
        platform: 'Huawei',
        fcmToken: 'fcm_token_3',
        status: 1,
        activated: 1,
        created: '2025-02-01',
        deleted: 0
      },
      {
        id: 4,
        etenUserID: 'EU1004',
        countryCode: '60',
        mobileNumber: '1223344556',
        password: 'hashed_pw_4',
        firstName: 'Syafiq',
        lastName: 'Zain',
        emailAddress: 'syafiq.zain@toyotires.com.my',
        gender: 'Male',
        race: 'Malay',
        state: 'Kuala Lumpur',
        level: 'Gold',
        memberSince: '2025-02-10',
        lastLogin: '2025-09-10 16:45:00',
        allow_warranty: 1,
        allow_order: 0,
        allow_billing: 1,
        allow_sale: 1,
        allow_user: 0,
        activationCode: 'ACT45678',
        isMaster: 0,
        device: 'iPad Pro',
        platform: 'iOS',
        fcmToken: 'fcm_token_4',
        status: 1,
        activated: 1,
        created: '2025-02-10',
        deleted: 0
      },
      {
        id: 5,
        etenUserID: 'EU1005',
        countryCode: '60',
        mobileNumber: '1678901234',
        password: 'hashed_pw_5',
        firstName: 'Nurul',
        lastName: 'Huda',
        emailAddress: 'nurul.huda@toyotires.com.my',
        gender: 'Female',
        race: 'Malay',
        state: 'Negeri Sembilan',
        level: 'Silver',
        memberSince: '2025-02-20',
        lastLogin: '2025-09-05 11:15:00',
        allow_warranty: 0,
        allow_order: 1,
        allow_billing: 0,
        allow_sale: 1,
        allow_user: 0,
        activationCode: 'ACT56789',
        isMaster: 0,
        device: 'Xiaomi 13',
        platform: 'Android',
        fcmToken: 'fcm_token_5',
        status: 1,
        activated: 1,
        created: '2025-02-20',
        deleted: 0
      },
      {
        id: 6,
        etenUserID: 'EU1006',
        countryCode: '60',
        mobileNumber: '1456789012',
        password: 'hashed_pw_6',
        firstName: 'Kumar',
        lastName: 'Raj',
        emailAddress: 'kumar.raj@toyotires.com.my',
        gender: 'Male',
        race: 'Indian',
        state: 'Perak',
        level: 'Silver',
        memberSince: '2025-03-01',
        lastLogin: '2025-08-29 13:30:00',
        allow_warranty: 1,
        allow_order: 1,
        allow_billing: 1,
        allow_sale: 0,
        allow_user: 0,
        activationCode: 'ACT67890',
        isMaster: 0,
        device: 'Huawei Mate 60',
        platform: 'Huawei',
        fcmToken: 'fcm_token_6',
        status: 1,
        activated: 1,
        created: '2025-03-01',
        deleted: 0
      },
      {
        id: 7,
        etenUserID: 'EU1007',
        countryCode: '60',
        mobileNumber: '1567890123',
        password: 'hashed_pw_7',
        firstName: 'Melissa',
        lastName: 'Tan',
        emailAddress: 'melissa.tan@toyotires.com.my',
        gender: 'Female',
        race: 'Chinese',
        state: 'Melaka',
        level: 'Silver',
        memberSince: '2025-03-15',
        lastLogin: '2025-08-25 08:40:00',
        allow_warranty: 1,
        allow_order: 0,
        allow_billing: 1,
        allow_sale: 0,
        allow_user: 0,
        activationCode: 'ACT78901',
        isMaster: 0,
        device: 'MacBook Air',
        platform: 'Web',
        fcmToken: 'fcm_token_7',
        status: 1,
        activated: 1,
        created: '2025-03-15',
        deleted: 0
      },
      {
        id: 8,
        etenUserID: 'EU1008',
        countryCode: '60',
        mobileNumber: '1678901235',
        password: 'hashed_pw_8',
        firstName: 'Amir',
        lastName: 'Hakim',
        emailAddress: 'amir.hakim@toyotires.com.my',
        gender: 'Male',
        race: 'Malay',
        state: 'Pahang',
        level: 'Silver',
        memberSince: '2025-04-01',
        lastLogin: '2025-08-18 15:50:00',
        allow_warranty: 0,
        allow_order: 1,
        allow_billing: 0,
        allow_sale: 1,
        allow_user: 0,
        activationCode: 'ACT89012',
        isMaster: 0,
        device: 'Samsung Tablet',
        platform: 'Android',
        fcmToken: 'fcm_token_8',
        status: 1,
        activated: 1,
        created: '2025-04-01',
        deleted: 0
      },
      {
        id: 9,
        etenUserID: 'EU1009',
        countryCode: '60',
        mobileNumber: '1789012345',
        password: 'hashed_pw_9',
        firstName: 'Zarina',
        lastName: 'Omar',
        emailAddress: 'zarina.omar@toyotires.com.my',
        gender: 'Female',
        race: 'Malay',
        state: 'Kelantan',
        level: 'Silver',
        memberSince: '2025-04-10',
        lastLogin: '2025-08-10 19:25:00',
        allow_warranty: 1,
        allow_order: 0,
        allow_billing: 1,
        allow_sale: 0,
        allow_user: 0,
        activationCode: 'ACT90123',
        isMaster: 0,
        device: 'iPhone 13',
        platform: 'iOS',
        fcmToken: 'fcm_token_9',
        status: 0,
        activated: 0,
        created: '2025-04-10',
        deleted: 0
      },
      {
        id: 10,
        etenUserID: 'EU1010',
        countryCode: '60',
        mobileNumber: '1890123456',
        password: 'hashed_pw_10',
        firstName: 'Faizal',
        lastName: 'Rahman',
        emailAddress: 'faizal.rahman@toyotires.com.my',
        gender: 'Male',
        race: 'Malay',
        state: 'Sabah',
        level: 'Silver',
        memberSince: '2025-04-20',
        lastLogin: '2025-08-01 12:05:00',
        allow_warranty: 0,
        allow_order: 1,
        allow_billing: 0,
        allow_sale: 1,
        allow_user: 0,
        activationCode: 'ACT01234',
        isMaster: 0,
        device: 'Windows Laptop',
        platform: 'Web',
        fcmToken: 'fcm_token_10',
        status: 1,
        activated: 1,
        created: '2025-04-20',
        deleted: 0
      }
    ];
  },

  getListEtenUserMini() {
    return Promise.resolve(this.getListEtenUserData().slice(0, 5));
  },

  getListEtenUserSmall() {
    return Promise.resolve(this.getListEtenUserData().slice(0, 10));
  },

  getListEtenUser() {
    return Promise.resolve(this.getListEtenUserData());
  }
};
