export const ListCatalogueService = {
  getListCatalogueData() {
    return [
      {
        id: 1,
        type: 'E-Wallet',
        imageURL: 'https://assets.bharian.com.my/images/articles/tng13jan_BHfield_image_socialmedia.var_1610544082.jpg',
        title: 'Touch ’n Go Reload RM20',
        sku: 'TNG20',
        valueType: 'RM',
        valueAmount: 20,
        description: 'Reload your Touch ’n Go eWallet instantly with RM20 credit.',
        terms: 'Valid for registered TNG accounts only.',
        instruction: 'Provide TNG eWallet number during redemption.',
        point1: 200,
        point2: 180,
        point3: 150,
        purpose: 'Reward',
        purposelD: 'PR001',
        totalqty: 500,
        availableqty: 420,
        expiry: '2025-12-31',
        isBirthday: 0,
        status: 1,
        created: '2025-01-01',
        deleted: 0
      },
      {
        id: 2,
        type: 'Voucher',
        imageURL: 'https://assets.offgamers.com/img/offer/kr_fdf75033-56ee-4ce6-929c-1f9c93a4c642_1b1c60fc-e950-4c62-8ee7-471d42484619.webp',
        title: 'RM50 Toyo Service Voucher',
        sku: 'TSV50',
        valueType: 'RM',
        valueAmount: 50,
        description: 'Redeemable at participating Toyo Tyre service centres nationwide.',
        terms: 'Valid for tyre service only. Not exchangeable for cash.',
        instruction: 'Present voucher code at counter.',
        point1: 500,
        point2: 480,
        point3: 450,
        purpose: 'Reward',
        purposelD: 'PR002',
        totalqty: 200,
        availableqty: 160,
        expiry: '2025-09-30',
        isBirthday: 0,
        status: 1,
        created: '2025-02-10',
        deleted: 0
      },
      {
        id: 3,
        type: 'Item',
        imageURL: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRdSHDEYMxmOB1Z63V0UB1ohMHGZ5cs5DG4zg&s',
        title: 'Toyo Tyres Cap',
        sku: 'TT-CAP01',
        valueType: 'Points',
        valueAmount: 300,
        description: 'Exclusive Toyo Tyres branded cap for loyal members.',
        terms: 'Limited to 1 per member.',
        instruction: 'Redeem online and collect at service centre.',
        point1: 300,
        point2: 280,
        point3: 250,
        purpose: 'Merchandise',
        purposelD: 'PR003',
        totalqty: 150,
        availableqty: 90,
        expiry: '2026-01-15',
        isBirthday: 0,
        status: 1,
        created: '2025-02-20',
        deleted: 0
      },
      {
        id: 4,
        type: 'E-Wallet',
        imageURL: 'https://assets.bharian.com.my/images/articles/tng13jan_BHfield_image_socialmedia.var_1610544082.jpg',
        title: 'Touch ’n Go Reload RM50',
        sku: 'TNG50',
        valueType: 'RM',
        valueAmount: 50,
        description: 'Get RM50 credit directly into your TNG eWallet.',
        terms: 'Limited to one redemption per week.',
        instruction: 'Provide TNG account number at redemption.',
        point1: 500,
        point2: 480,
        point3: 450,
        purpose: 'Reward',
        purposelD: 'PR004',
        totalqty: 300,
        availableqty: 250,
        expiry: '2025-11-30',
        isBirthday: 1,
        status: 1,
        created: '2025-03-01',
        deleted: 0
      },
      {
        id: 5,
        type: 'Voucher',
        imageURL: 'https://assets.offgamers.com/img/offer/kr_fdf75033-56ee-4ce6-929c-1f9c93a4c642_1b1c60fc-e950-4c62-8ee7-471d42484619.webp',
        title: 'RM100 Toyo Voucher',
        sku: 'TV100',
        valueType: 'RM',
        valueAmount: 100,
        description: 'Redeem for Toyo Tyres or merchandise at official outlets.',
        terms: 'Valid for one-time use.',
        instruction: 'Show e-voucher QR code at redemption.',
        point1: 1000,
        point2: 950,
        point3: 900,
        purpose: 'Reward',
        purposelD: 'PR005',
        totalqty: 100,
        availableqty: 85,
        expiry: '2025-12-15',
        isBirthday: 0,
        status: 1,
        created: '2025-03-15',
        deleted: 0
      },
      {
        id: 6,
        type: 'Item',
        imageURL: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRdSHDEYMxmOB1Z63V0UB1ohMHGZ5cs5DG4zg&s',
        title: 'Toyo Sports Bottle',
        sku: 'TT-BOT01',
        valueType: 'Points',
        valueAmount: 200,
        description: 'Durable sports bottle with Toyo branding.',
        terms: 'Available while stocks last.',
        instruction: 'Collect at Toyo service centre after redemption.',
        point1: 200,
        point2: 180,
        point3: 150,
        purpose: 'Merchandise',
        purposelD: 'PR006',
        totalqty: 300,
        availableqty: 240,
        expiry: '2026-02-01',
        isBirthday: 0,
        status: 1,
        created: '2025-04-01',
        deleted: 0
      },
      {
        id: 7,
        type: 'Voucher',
        imageURL: 'https://assets.offgamers.com/img/offer/kr_fdf75033-56ee-4ce6-929c-1f9c93a4c642_1b1c60fc-e950-4c62-8ee7-471d42484619.webp',
        title: 'Free Wheel Alignment Voucher',
        sku: 'WA001',
        valueType: 'Service',
        valueAmount: 1,
        description: 'One free wheel alignment service at Toyo centres.',
        terms: 'Valid with purchase of 2 or more Toyo tyres.',
        instruction: 'Book service in advance.',
        point1: 600,
        point2: 580,
        point3: 550,
        purpose: 'Service',
        purposelD: 'PR007',
        totalqty: 200,
        availableqty: 180,
        expiry: '2025-10-31',
        isBirthday: 0,
        status: 1,
        created: '2025-04-15',
        deleted: 0
      },
      {
        id: 8,
        type: 'Item',
        imageURL: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRdSHDEYMxmOB1Z63V0UB1ohMHGZ5cs5DG4zg&s',
        title: 'Toyo T-Shirt Limited Edition',
        sku: 'TT-TSHIRT01',
        valueType: 'Points',
        valueAmount: 400,
        description: 'Limited edition Toyo Tyres t-shirt for members.',
        terms: 'Sizes subject to availability.',
        instruction: 'Redeem online, collect in-store.',
        point1: 400,
        point2: 380,
        point3: 350,
        purpose: 'Merchandise',
        purposelD: 'PR008',
        totalqty: 100,
        availableqty: 60,
        expiry: '2025-12-01',
        isBirthday: 1,
        status: 1,
        created: '2025-05-01',
        deleted: 0
      },
      {
        id: 9,
        type: 'E-Wallet',
        imageURL: 'https://assets.bharian.com.my/images/articles/tng13jan_BHfield_image_socialmedia.var_1610544082.jpg',
        title: 'Touch ’n Go Reload RM100',
        sku: 'TNG100',
        valueType: 'RM',
        valueAmount: 100,
        description: 'Enjoy RM100 reload for your Touch ’n Go eWallet.',
        terms: 'Valid once per account monthly.',
        instruction: 'Enter TNG ID during redemption.',
        point1: 1000,
        point2: 950,
        point3: 900,
        purpose: 'Reward',
        purposelD: 'PR009',
        totalqty: 150,
        availableqty: 120,
        expiry: '2025-11-15',
        isBirthday: 0,
        status: 1,
        created: '2025-05-20',
        deleted: 0
      },
      {
        id: 10,
        type: 'Item',
        imageURL: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRdSHDEYMxmOB1Z63V0UB1ohMHGZ5cs5DG4zg&s',
        title: 'Toyo Umbrella',
        sku: 'TT-UMB01',
        valueType: 'Points',
        valueAmount: 350,
        description: 'Large Toyo branded umbrella for rainy days.',
        terms: 'Limited edition item.',
        instruction: 'Collect at Toyo branches.',
        point1: 350,
        point2: 330,
        point3: 300,
        purpose: 'Merchandise',
        purposelD: 'PR010',
        totalqty: 120,
        availableqty: 100,
        expiry: '2026-03-01',
        isBirthday: 0,
        status: 1,
        created: '2025-06-01',
        deleted: 0
      }
    ];
  },

  getListCatalogueMini() {
    return Promise.resolve(this.getListCatalogueData().slice(0, 5));
  },

  getListCatalogueSmall() {
    return Promise.resolve(this.getListCatalogueData().slice(0, 10));
  },

  getListCatalogue() {
    return Promise.resolve(this.getListCatalogueData());
  }
};
