export const ListTyreService = {
    getListTyreData() {
        return [
            {
                id: 1,
                warrantyRegisterID: 1001,
                materialid: "81114NE0304175H",
                pattern: 'Proxes T1R',
                rimDiameter: 17,
                aspectRatio: '45',
                sectionWidth: '215',
                tyreSize: '215/45R17',
                loadIndex: '91',
                plyRating: 'XL',
                deleted: null,
                status: 'Non-Waranty',
                size: '215/45R17',
                origin: 'Japan',
                desc: 'High-performance tire for sports cars',
                mfgcode: 'MFG-2025-001',
                tyresize: 'Passenger Car',
                tyrespec: '91W',
                weekcode: '3524'
            },
            {
                id: 2,
                warrantyRegisterID: 1002,
                materialid: "81114NE0304176H",
                pattern: 'Open Country A/T III',
                rimDiameter: 18,
                aspectRatio: '65',
                sectionWidth: '265',
                tyreSize: '265/65R18',
                loadIndex: '114',
                plyRating: '10PR',
                deleted: null,
                status: 'Waranty',
                size: '265/65R18',
                origin: 'Thailand',
                desc: 'All-terrain tire designed for SUVs and light trucks',
                mfgcode: 'MFG-2025-002',
                tyresize: 'SUV',
                tyrespec: '114S',
                weekcode: '3324'
            },
            {
                id: 3,
                warrantyRegisterID: 1003,
                materialid: "81114NE0304177H",
                pattern: 'Proxes Sport',
                rimDiameter: 19,
                aspectRatio: '40',
                sectionWidth: '245',
                tyreSize: '245/40R19',
                loadIndex: '98',
                plyRating: 'XL',
                deleted: null,
                status: 'Waranty',
                size: '245/40R19',
                origin: 'Japan',
                desc: 'Ultra high-performance tire for superior grip and handling',
                mfgcode: 'MFG-2025-003',
                tyresize: 'Passenger Car',
                tyrespec: '98Y',
                weekcode: '3224'
            },
            {
                id: 4,
                warrantyRegisterID: 1004,
                materialid: "81114NE0304178H",
                pattern: 'Observe GSi-6',
                rimDiameter: 16,
                aspectRatio: '55',
                sectionWidth: '205',
                tyreSize: '205/55R16',
                loadIndex: '91',
                plyRating: 'Standard',
                deleted: null,
                status: 'Non-Waranty',
                size: '205/55R16',
                origin: 'Malaysia',
                desc: 'Winter tire designed for enhanced performance on snow and ice',
                mfgcode: 'MFG-2025-004',
                tyresize: 'Passenger Car',
                tyrespec: '91H',
                weekcode: '3124'
            },
            {
                id: 5,
                warrantyRegisterID: 1005,
                materialid: "81114NE0304179H",
                pattern: 'Open Country M/T',
                rimDiameter: 17,
                aspectRatio: '70',
                sectionWidth: '285',
                tyreSize: '285/70R17',
                loadIndex: '121',
                plyRating: '10PR',
                deleted: null,
                status: 'Waranty',
                size: '285/70R17',
                origin: 'Thailand',
                desc: 'Mud-terrain tire built for rugged off-road performance',
                mfgcode: 'MFG-2025-005',
                tyresize: 'Truck',
                tyrespec: '121Q',
                weekcode: '2924'
            },
            {
                id: 6,
                warrantyRegisterID: 1006,
                materialid: "81114NE0304180H",
                pattern: 'Proxes R1R',
                rimDiameter: 15,
                aspectRatio: '50',
                sectionWidth: '195',
                tyreSize: '195/50R15',
                loadIndex: '82',
                plyRating: 'Standard',
                deleted: null,
                status: 'Non-Waranty',
                size: '195/50R15',
                origin: 'Japan',
                desc: 'Street sports tire for superior cornering and braking',
                mfgcode: 'MFG-2025-006',
                tyresize: 'Passenger Car',
                tyrespec: '82V',
                weekcode: '3024'
            },
            {
                id: 7,
                warrantyRegisterID: 1007,
                materialid: "81114NE0304181H",
                pattern: 'Open Country H/T',
                rimDiameter: 20,
                aspectRatio: '55',
                sectionWidth: '275',
                tyreSize: '275/55R20',
                loadIndex: '113',
                plyRating: '8PR',
                deleted: null,
                status: 'Waranty',
                size: '275/55R20',
                origin: 'Malaysia',
                desc: 'Highway terrain tire optimized for smooth rides',
                mfgcode: 'MFG-2025-007',
                tyresize: 'Truck',
                tyrespec: '113T',
                weekcode: '3424'
            },
            {
                id: 8,
                warrantyRegisterID: 1008,
                materialid: "81114NE0304182H",
                pattern: 'Proxes ST III',
                rimDiameter: 19,
                aspectRatio: '45',
                sectionWidth: '255',
                tyreSize: '255/45R19',
                loadIndex: '104',
                plyRating: 'XL',
                deleted: null,
                status: 'Non-Waranty',
                size: '255/45R19',
                origin: 'Japan',
                desc: 'High-performance SUV tire for stability and comfort',
                mfgcode: 'MFG-2025-008',
                tyresize: 'SUV',
                tyrespec: '104W',
                weekcode: '3724'
            },
            {
                id: 9,
                warrantyRegisterID: 1009,
                materialid: "81114NE0304183H",
                pattern: 'Open Country R/T',
                rimDiameter: 17,
                aspectRatio: '65',
                sectionWidth: '265',
                tyreSize: '265/65R17',
                loadIndex: '120',
                plyRating: '10PR',
                deleted: null,
                status: 'Non-Waranty',
                size: '265/65R17',
                origin: 'Thailand',
                desc: 'Rugged terrain tire built for mixed off-road and highway driving',
                mfgcode: 'MFG-2025-009',
                tyresize: 'Truck',
                tyrespec: '120S',
                weekcode: '3624'
            },
            {
                id: 10,
                warrantyRegisterID: 1010,
                materialid: "81114NE0304184H",
                pattern: 'Proxes T1 Sport SUV',
                rimDiameter: 21,
                aspectRatio: '35',
                sectionWidth: '275',
                tyreSize: '275/35R21',
                loadIndex: '103',
                plyRating: 'XL',
                deleted: null,
                status: 'Waranty',
                size: '275/35R21',
                origin: 'Japan',
                desc: 'Premium performance SUV tire for ultimate grip and speed',
                mfgcode: 'MFG-2025-010',
                tyresize: 'SUV',
                tyrespec: '103Y',
                weekcode: '3824'
            }
        ];
    },

    getListTwpTyresData() {
        return [
            { id: 1, materialid: "81114NE0304175H", tyreSize: '215/45R17', pattern: 'Proxes T1R' },
            { id: 2, materialid: "81114NE0304176H", tyreSize: '265/65R18', pattern: 'Open Country A/T III' },
            { id: 3, materialid: "81114NE0304177H", tyreSize: '245/40R19', pattern: 'Proxes Sport' },
            { id: 4, materialid: "81114NE0304179H", tyreSize: '285/70R17', pattern: 'Open Country M/T' }
        ];
    },

    getListTyreMini() {
        return Promise.resolve(this.getListTyreData().slice(0, 5));
    },

    getListTyreSmall() {
        return Promise.resolve(this.getListTyreData().slice(0, 10));
    },

    getListTyre() {
        return Promise.resolve(this.getListTyreData());
    },
    getListTwpTyres() {
        return Promise.resolve(this.getListTwpTyresData());
    }
};
