export const ListBackOrderService = {
    getListBackOrderData() {
        return [
            {
                id: 1,
                etenUserListID: 'U12345',
                etenUserID: 'U67890',
                custAccountNo: '6080100900',
                customerName: 'PS Tyres & Battery Auto Services Sdn. Bhd',
                signboard: 'T10',
                progress: 85,
                salesOrg: 'SO001',
                distributionChannel: 'ETEN',
                division: 'DIV01',
                priceGroup: 'PG01',
                sapOrderType: 'NORMAL',
                customerCondGrp: 'CCG1',
                shippingCond: 'Standard',
                storageLocation: 'LOC01',
                orderDesc: 'General tyre order for regular maintenance',
                channel: 'ETEN',
                deliveryType: 'DELIVER',
                deliveryDate: '2023-10-15',
                boOrderNo: 'BO1001',
                backOrderArray: ['BO1001-1', 'BO1001-2'],
                fulfillArray: ['FU1001'],
                orderStatus: 3,
                shipTo: '6601203021',
                expiry: '2023-11-15',
                created: '2023-10-01',
                modified: '2023-10-05'
            },
            {
                id: 2,
                etenUserListID: 'U23456',
                etenUserID: 'U78901',
                custAccountNo: '6080102300',
                customerName: 'Toyo Auto Centre UHP Tyres Sdn Bhd',
                signboard: 'TTC',
                progress: 60,
                salesOrg: 'SO002',
                distributionChannel: 'ADMIN',
                division: 'DIV02',
                priceGroup: 'PG02',
                sapOrderType: 'DIRECTSHIP',
                customerCondGrp: 'CCG2',
                shipTo: '6601203021',
                shippingCond: 'Express',
                storageLocation: 'LOC02',
                orderDesc: 'Special high-performance tyres for event stock',
                channel: 'ADMIN',
                deliveryType: 'SELFCOLLECT',
                deliveryDate: '2023-10-20',
                boOrderNo: 'BO1002',
                backOrderArray: [],
                fulfillArray: ['FU1002'],
                orderStatus: 1,
                expiry: '2023-11-20',
                created: '2023-10-02',
                modified: '2023-10-06'
            },
            {
                id: 3,
                etenUserListID: 'U34567',
                etenUserID: 'U89012',
                custAccountNo: '6080102301',
                customerName: 'Tek Ming Auto Service Sdn. Bhd.',
                signboard: 'TPC',
                progress: 40,
                salesOrg: 'SO003',
                division: 'DIV03',
                priceGroup: 'PG03',
                sapOrderType: 'OWN',
                customerCondGrp: 'CCG3',
                shipTo: '6601203021',
                shippingCond: 'Lalamove',
                storageLocation: 'LOC03',
                orderDesc: 'Urgent replacement order for bulk tyres',
                channel: 'CARES',
                deliveryType: 'LALAMOVE',
                deliveryDate: '2023-10-25',
                boOrderNo: 'BO1003',
                backOrderArray: ['BO1003-1'],
                fulfillArray: [],
                orderStatus: 2,
                expiry: '2023-11-25',
                created: '2023-10-03',
                modified: '2023-10-07'
            },
            {
                id: 4,
                etenUserListID: 'U45678',
                etenUserID: 'U90123',
                custAccountNo: '6080102302',
                customerName: 'Apex Tyre & Car Care',
                signboard: 'TST',
                progress: 90,
                salesOrg: 'SO004',
                division: 'DIV04',
                priceGroup: 'PG04',
                sapOrderType: 'NORMAL',
                customerCondGrp: 'CCG4',
                shipTo: '6601203021',
                shippingCond: 'Standard',
                storageLocation: 'LOC04',
                orderDesc: 'Monthly supply of tyre sealants',
                channel: 'ETEN',
                deliveryType: 'DELIVER',
                deliveryDate: '2023-10-18',
                boOrderNo: 'BO1004',
                backOrderArray: [],
                fulfillArray: ['FU1004', 'FU1004-2'],
                orderStatus: 3,
                expiry: '2023-11-18',
                created: '2023-10-04',
                modified: '2023-10-08'
            },
            {
                id: 5,
                etenUserListID: 'U56789',
                etenUserID: 'U01234',
                custAccountNo: '6080114400',
                customerName: 'JS Motorsports Sdn Bhd',
                signboard: 'TSS',
                progress: 75,
                salesOrg: 'SO005',
                division: 'DIV05',
                priceGroup: 'PG05',
                sapOrderType: 'OWN',
                customerCondGrp: 'CCG5',
                shipTo: '6601203021',
                shippingCond: 'Express',
                storageLocation: 'LOC05',
                orderDesc: 'Tyres for track performance customers',
                channel: 'ADMIN',
                deliveryType: 'SELFCOLLECT',
                deliveryDate: '2023-10-22',
                boOrderNo: 'BO1005',
                backOrderArray: ['BO1005-1'],
                fulfillArray: [],
                orderStatus: 1,
                expiry: '2023-11-22',
                created: '2023-10-05',
                modified: '2023-10-09'
            },
            {
                id: 6,
                etenUserListID: 'U67890',
                etenUserID: 'U12345',
                custAccountNo: '6080125300',
                customerName: 'Weng Tat Tyre Service',
                signboard: 'TTX',
                progress: 100,
                salesOrg: 'SO006',
                division: 'DIV06',
                priceGroup: 'PG06',
                sapOrderType: 'NORMAL',
                customerCondGrp: 'CCG6',
                shipTo: '6601203021',
                shippingCond: 'Standard',
                storageLocation: 'LOC06',
                orderDesc: 'Replacement order for standard car tyres',
                channel: 'CARES',
                deliveryType: 'LALAMOVE',
                deliveryDate: '2023-10-29',
                boOrderNo: 'BO1006',
                backOrderArray: [],
                fulfillArray: ['FU1006'],
                orderStatus: 4,
                expiry: '2023-11-29',
                created: '2023-10-06',
                modified: '2023-10-10'
            },
            {
                id: 7,
                etenUserListID: 'U78901',
                etenUserID: 'U23456',
                custAccountNo: '6080126701',
                customerName: 'Tyrax Auto Sdn Bhd (Toyo Tires)',
                signboard: 'TC',
                progress: 55,
                salesOrg: 'SO007',
                division: 'DIV07',
                priceGroup: 'PG07',
                sapOrderType: 'OWN',
                customerCondGrp: 'CCG7',
                shipTo: '6601203021',
                shippingCond: 'Express',
                storageLocation: 'LOC07',
                orderDesc: 'Toyo tyre promotional shipment',
                channel: 'ETEN',
                deliveryType: 'DELIVER',
                deliveryDate: '2023-11-02',
                boOrderNo: 'BO1007',
                backOrderArray: ['BO1007-1', 'BO1007-2'],
                fulfillArray: [],
                orderStatus: 2,
                expiry: '2023-11-02',
                created: '2023-10-07',
                modified: '2023-10-11'
            },
            {
                id: 8,
                etenUserListID: 'U89012',
                etenUserID: 'U34567',
                custAccountNo: '608015202',
                customerName: 'CHY Tyre & Autocare Centre',
                signboard: 'TAC',
                progress: 80,
                salesOrg: 'SO008',
                division: 'DIV08',
                priceGroup: 'PG08',
                sapOrderType: 'NORMAL',
                customerCondGrp: 'CCG8',
                shipTo: '6601203021',
                shippingCond: 'Standard',
                storageLocation: 'LOC08',
                orderDesc: 'Tyre restock for regional distribution',
                channel: 'ADMIN',
                deliveryType: 'SELFCOLLECT',
                deliveryDate: '2023-11-05',
                boOrderNo: 'BO1008',
                backOrderArray: [],
                fulfillArray: ['FU1008'],
                orderStatus: 3,
                expiry: '2023-11-05',
                created: '2023-10-08',
                modified: '2023-10-12'
            },
            {
                id: 9,
                etenUserListID: 'U90123',
                etenUserID: 'U45678',
                custAccountNo: '608017502',
                customerName: 'Hupshun Tyres Auto Car Care Sdn Bhd',
                signboard: 'TAC',
                progress: 20,
                salesOrg: 'SO009',
                division: 'DIV09',
                priceGroup: 'PG09',
                sapOrderType: 'OWN',
                customerCondGrp: 'CCG9',
                shipTo: '6601203021',
                shippingCond: 'Express',
                storageLocation: 'LOC09',
                orderDesc: 'Return order for incorrect stock',
                channel: 'CARES',
                deliveryType: 'LALAMOVE',
                deliveryDate: '2023-11-10',
                boOrderNo: 'BO1009',
                backOrderArray: ['BO1009-1'],
                fulfillArray: [],
                orderStatus: 5,
                expiry: '2023-11-10',
                created: '2023-10-09',
                modified: '2023-10-13'
            },
            {
                id: 10,
                etenUserListID: 'U01234',
                etenUserID: 'U56789',
                custAccountNo: '6080143301',
                customerName: 'Ah Man Tyre Service Centre Sdn Bhd',
                signboard: 'T10',
                progress: 95,
                salesOrg: 'SO010',
                division: 'DIV10',
                priceGroup: 'PG10',
                sapOrderType: 'NORMAL',
                customerCondGrp: 'CCG10',
                shipTo: '6601203021',
                shippingCond: 'Standard',
                storageLocation: 'LOC10',
                orderDesc: 'Bulk purchase for regional distribution',
                channel: 'ETEN',
                deliveryType: 'DELIVER',
                deliveryDate: '2023-11-15',
                boOrderNo: 'BO1010',
                backOrderArray: [],
                fulfillArray: ['FU1010'],
                orderStatus: 1,
                expiry: '2023-11-15',
                created: '2023-10-10',
                modified: '2023-10-14'
            }
        ];
    },

    getListBackOrderMini() {
        return Promise.resolve(this.getListBackOrderData().slice(0, 5));
    },

    getListBackOrderSmall() {
        return Promise.resolve(this.getListBackOrderData().slice(0, 10));
    },

    getListBackOrder() {
        return Promise.resolve(this.getListBackOrdernData());
    }
};
