export const listWarantyClaimService = { 
  // Main function to return all events
  getListWarantyData() {
    return [
      {
        id: 1,
        refNo: "CLM-2025-001",
        claimDate: "2025-01-12",
        dealerName: "Toyo Tires Sepang Dealer",
        claimType: "Warranty",
        audience: "TC",
        isSurvey: 0,
        point1: 85,
        point2: 90,
        point3: 95,
        title: "Toyo Tires Drift Challenge 2025",
        image1URL: "https://example.com/images/drift1.jpg",
        image2URL: "https://example.com/images/drift2.jpg",
        image3URL: "https://example.com/images/drift3.jpg",
        desc: "Experience the thrill of high-speed drifting powered by Toyo Tires. Join us for a weekend of motorsport excitement!",
        location: "Sepang International Circuit, Malaysia",
        publishDate: "2025-01-10",
        startDate: "2025-02-15",
        endDate: "2025-02-16",
        view: 542,
        status: 1,
        created: "2025-01-05",
        deleted: null,
      },
      {
        id: 2,
        refNo: "CLM-2025-002",
        claimDate: "2025-03-05",
        dealerName: "Toyo Tires KLCC Dealer",
        claimType: "Rebate",
        audience: "TC",
        isSurvey: 1,
        point1: 78,
        point2: 85,
        point3: 88,
        title: "Toyo Tires Auto Show 2025",
        image1URL: "https://example.com/images/autoshow1.jpg",
        image2URL: "https://example.com/images/autoshow2.jpg",
        image3URL: "https://example.com/images/autoshow3.jpg",
        desc: "Showcasing the latest Toyo Tires technology and car exhibitions featuring premium vehicles.",
        location: "Kuala Lumpur Convention Centre",
        publishDate: "2025-03-01",
        startDate: "2025-03-20",
        endDate: "2025-03-23",
        view: 890,
        status: 5,
        created: "2025-02-20",
        deleted: null,
      },
      {
        id: 3,
        refNo: "CLM-2025-003",
        claimDate: "2025-04-10",
        dealerName: "Toyo Tires Summit Dealer",
        claimType: "Warranty",
        audience: "ALL",
        isSurvey: 0,
        point1: 92,
        point2: 86,
        point3: 80,
        title: "Toyo Tires Dealer Summit 2025",
        image1URL: "https://example.com/images/dealer1.jpg",
        image2URL: "https://example.com/images/dealer2.jpg",
        image3URL: "https://example.com/images/dealer3.jpg",
        desc: "Annual dealer summit to strengthen partnerships and explore new opportunities with Toyo Tires.",
        location: "Shangri-La Hotel, Kuala Lumpur",
        publishDate: "2025-04-05",
        startDate: "2025-04-25",
        endDate: "2025-04-26",
        view: 340,
        status: 0,
        created: "2025-04-01",
        deleted: null,
      },
      {
        id: 4,
        refNo: "CLM-2025-004",
        claimDate: "2025-05-05",
        dealerName: "Toyo Tires Penang Dealer",
        claimType: "Promotion",
        audience: "TC",
        isSurvey: 0,
        point1: 70,
        point2: 75,
        point3: 88,
        title: "Toyo Tires Green Mobility Expo",
        image1URL: "https://example.com/images/green1.jpg",
        image2URL: "https://example.com/images/green2.jpg",
        image3URL: "https://example.com/images/green3.jpg",
        desc: "Discover Toyo Tires' commitment to sustainability with innovative tire solutions for greener mobility.",
        location: "Penang Eco Park",
        publishDate: "2025-05-01",
        startDate: "2025-05-18",
        endDate: "2025-05-20",
        view: 720,
        status: 2,
        created: "2025-04-28",
        deleted: null,
      },
      {
        id: 5,
        refNo: "CLM-2025-005",
        claimDate: "2025-06-10",
        dealerName: "Toyo Tires Johor Dealer",
        claimType: "Warranty",
        audience: "ETEN",
        isSurvey: 0,
        point1: 95,
        point2: 88,
        point3: 82,
        title: "Toyo Tires Off-Road Challenge",
        image1URL: "https://example.com/images/offroad1.jpg",
        image2URL: "https://example.com/images/offroad2.jpg",
        image3URL: "https://example.com/images/offroad3.jpg",
        desc: "Extreme off-road competition powered by Toyo Tires, featuring rugged terrains and ultimate endurance.",
        location: "Johor Bahru Off-Road Track",
        publishDate: "2025-06-01",
        startDate: "2025-06-20",
        endDate: "2025-06-21",
        view: 640,
        status: 4,
        created: "2025-05-25",
        deleted: null,
      },
      {
        id: 6,
        refNo: "CLM-2025-006",
        claimDate: "2025-07-10",
        dealerName: "Toyo Tires UM Dealer",
        claimType: "Rebate",
        audience: "TC",
        isSurvey: true,
        point1: 80,
        point2: 85,
        point3: 92,
        title: "Toyo Tires Innovation Hackathon",
        image1URL: "https://example.com/images/hackathon1.jpg",
        image2URL: "https://example.com/images/hackathon2.jpg",
        image3URL: "https://example.com/images/hackathon3.jpg",
        desc: "A hackathon for young innovators to create solutions for the future of tire technology and mobility.",
        location: "Universiti Malaya, Kuala Lumpur",
        publishDate: "2025-07-05",
        startDate: "2025-07-25",
        endDate: "2025-07-27",
        view: 430,
        status: 3,
        created: "2025-07-01",
        deleted: null,
      },
    ];
  },

  // Return first 5 events
  getListEventMini() {
    return Promise.resolve(this.getListEventData().slice(0, 5));
  },

  // Return first 10 events
  getListEventSmall() {
    return Promise.resolve(this.getListEventData().slice(0, 10));
  },

  // Return all events
  getListEvent() {
    return Promise.resolve(this.getListEventData());
  },
};
