export const ListEtenService = {
  getListEtenData() {
    return [
      {
        memberCode: 'E346572',
        custAccountNo: '6080100900',
        companyName1: 'PS Tyres & Battery Auto Services Sdn. Bhd',
        companyName2: '',
        companyName3: '',
        companyName4: '',
        companyRegNo: 'MY123456789',
        salesTaxNo: 'SST123456',
        serviceTaxNo: 'STX120987',
        tinNo: '1256734321',
        vatNo: '0976213456',
        addressLine1: '123 Toyo Road',
        addressLine2: 'Toyo Industrial Park',
        addressLine3: '',
        addressLine4: '',
        city: 'Kuala Lumpur',
        postcode: '50000',
        state: 'Kuala Lumpur',
        country: 'Malaysia',
        mapLatitude: '3.1390',
        mapLongitude: '101.6869',
        phoneNumber: '+60 3-1234 5678',
        mobilreNumber: '+60 19-1234 567',
        emailAddress: 'sales@toyotires.com.my',
        accountType: 'Retailer',
        priceGroup: 'A',
        priceProcedure: 'Standard',
        customerAccountGroup: 'Group1',
        customerCondGrp: 'Cond1',
        paymentTerms: 'NET 30',
        riskCategory: 'Low',
        creditLimit: 50000,
        pricelist: '01',
        signboardType: 'T10',
        signboardBrand: 'Toyo',
        salesOffice: 'Kuala Lumpur',
        salesDistrict: 'Central',
        shippingCond: 'RE',
        accountCreation: '2023-01-15',
        showOnList: 1,
        ifFamilyChannel: 0,
        allowLalamove: 1,
        startingSalesAmt: 1000,
        status: 0
      },
      {
        memberCode: 'E234176',
        custAccountNo: '6080102300',
        companyName1: 'Toyo Auto Centre UHP Tyres Sdn Bhd',
        companyName2: '',
        companyName3: '',
        companyName4: '',
        companyRegNo: 'MY987654321',
        salesTaxNo: 'SST654321',
        serviceTaxNo: 's',
        tinNo: '19264590234',
        vatNo: '14563278993',
        addressLine1: '456 Tire Street',
        addressLine2: 'Johor Bahru Industrial Area',
        addressLine3: '',
        addressLine4: '',
        city: 'Johor Bahru',
        postcode: '80000',
        state: 'Johor',
        country: 'Malaysia',
        mapLatitude: '1.4927',
        mapLongitude: '103.7414',
        phoneNumber: '+60 7-2345 678',
        mobilreNumber: '+60 16-2345 678',
        emailAddress: 'johor@toyotires.com.my',
        accountType: 'Wholesaler',
        priceGroup: 'B',
        priceProcedure: 'Premium',
        customerAccountGroup: 'Group2',
        customerCondGrp: 'Cond2',
        paymentTerms: 'NET 45',
        riskCategory: 'Medium',
        creditLimit: 100000,
        pricelist: '02',
        signboardType: 'TAC',
        signboardBrand: 'Toyo',
        salesOffice: 'Johor',
        salesDistrict: 'Southern',
        shippingCond: 'TP',
        accountCreation: '2023-02-20',
        showOnList: 1,
        ifFamilyChannel: 1,
        allowLalamove: 0,
        startingSalesAmt: 2000,
        status: 1,
      },
      {
        memberCode: 'E127568',
        custAccountNo: '6080102301',
        companyName1: 'Tek Ming Auto Service Sdn. Bhd.',
        companyName2: '',
        companyName3: '',
        companyName4: '',
        companyRegNo: 'MY192837465',
        salesTaxNo: 'SST192837',
        serviceTaxNo: '',
        tinNo: '',
        vatNo: '',
        addressLine1: '789 Rubber Lane',
        addressLine2: 'Penang Industrial Estate',
        addressLine3: '',
        addressLine4: '',
        city: 'George Town',
        postcode: '10200',
        state: 'Penang',
        country: 'Malaysia',
        mapLatitude: '5.4145',
        mapLongitude: '100.3288',
        phoneNumber: '+60 4-3456 789',
        mobilreNumber: '+60 12-3456 789',
        emailAddress: 'penang@toyotires.com.my',
        accountType: 'Retailer',
        priceGroup: 'A',
        priceProcedure: 'Standard',
        customerAccountGroup: 'Group3',
        customerCondGrp: 'Cond3',
        paymentTerms: 'NET 30',
        riskCategory: 'Low',
        creditLimit: 60000,
        pricelist: '03',
        signboardType: 'TSS',
        signboardBrand: 'Toyo',
        salesOffice: 'Penang',
        salesDistrict: 'Northern',
        shippingCond: 'RE',
        accountCreation: '2023-03-10',
        showOnList: 1,
        ifFamilyChannel: 0,
        allowLalamove: 1,
        startingSalesAmt: 1500,
        status: 1,
      },
      {
        memberCode: 'E127823',
        custAccountNo: '6080102302',
        companyName1: 'Apex Tyre & Car Care',
        companyName2: '',
        companyName3: '',
        companyName4: '',
        companyRegNo: 'MY564738291',
        salesTaxNo: 'SST564738',
        serviceTaxNo: '',
        tinNo: '',
        vatNo: '',
        addressLine1: '321 Tire Avenue',
        addressLine2: 'Subang Industrial Park',
        addressLine3: '',
        addressLine4: '',
        city: 'Subang Jaya',
        postcode: '93000',
        state: 'Selangor',
        country: 'Malaysia',
        mapLatitude: '1.5533',
        mapLongitude: '110.3593',
        phoneNumber: '+60 82-4567 890',
        mobilreNumber: '+60 18-4567 890',
        emailAddress: 'selangor@toyotires.com.my',
        accountType: 'Wholesaler',
        priceGroup: 'B',
        priceProcedure: 'Premium',
        customerAccountGroup: 'Group4',
        customerCondGrp: 'Cond4',
        paymentTerms: 'NET 60',
        riskCategory: 'High',
        creditLimit: 120000,
        pricelist: '04',
        signboardType: 'TST',
        signboardBrand: 'Toyo',
        salesOffice: 'Kuching',
        salesDistrict: 'East',
        shippingCond: 'TP',
        accountCreation: '2023-04-05',
        showOnList: 1,
        ifFamilyChannel: 1,
        allowLalamove: 0,
        startingSalesAmt: 2500,
        status: 1,
      },
      {
        memberCode: 'E748235',
        custAccountNo: '6080114400',
        companyName1: 'JS Motorsports Sdn Bhd',
        companyName2: '',
        companyName3: '',
        companyName4: '',
        companyRegNo: 'MY837465192',
        salesTaxNo: 'SST837465',
        serviceTaxNo: '',
        tinNo: '',
        vatNo: '',
        addressLine1: '654 Tire Bay',
        addressLine2: 'Petaling Industrial Zone',
        addressLine3: '',
        addressLine4: '',
        city: 'Petaling Jaya',
        postcode: '07000',
        state: 'Selangor',
        country: 'Malaysia',
        mapLatitude: '6.3674',
        mapLongitude: '99.7632',
        phoneNumber: '+60 4-5678 901',
        mobilreNumber: '+60 17-5678 901',
        emailAddress: 'petaling@toyotires.com.my',
        accountType: 'Retailer',
        priceGroup: 'A',
        priceProcedure: 'Standard',
        customerAccountGroup: 'Group5',
        customerCondGrp: 'Cond5',
        paymentTerms: 'NET 30',
        riskCategory: 'Low',
        creditLimit: 70000,
        pricelist: '05',
        signboardType: 'T10',
        signboardBrand: 'Toyo',
        salesOffice: 'Langkawi',
        salesDistrict: 'North',
        shippingCond: 'RE',
        accountCreation: '2023-05-12',
        showOnList: 1,
        ifFamilyChannel: 0,
        allowLalamove: 1,
        startingSalesAmt: 1800,
        status: 1,
      },
      {
        memberCode: 'E325632',
        custAccountNo: '6080125300',
        companyName1: 'Weng Tat Tyre Service',
        companyName2: '',
        companyName3: '',
        companyName4: '',
        companyRegNo: 'MY475839201',
        salesTaxNo: 'SST475839',
        serviceTaxNo: '',
        tinNo: '',
        vatNo: '',
        addressLine1: '987 Tire Road',
        addressLine2: 'Pantai Merdeka Free Trade Zone',
        addressLine3: '',
        addressLine4: '',
        city: 'Pantai Merdeka',
        postcode: '87000',
        state: 'Kedah',
        country: 'Malaysia',
        mapLatitude: '5.2734',
        mapLongitude: '115.2414',
        phoneNumber: '+60 8-7654 321',
        mobilreNumber: '+60 19-8765 432',
        emailAddress: 'labuan@toyotires.com.my',
        accountType: 'Wholesaler',
        priceGroup: 'B',
        priceProcedure: 'Premium',
        customerAccountGroup: 'Group6',
        customerCondGrp: 'Cond6',
        paymentTerms: 'NET 45',
        riskCategory: 'Medium',
        creditLimit: 90000,
        pricelist: '01',
        signboardType: 'TAC',
        signboardBrand: 'Toyo',
        salesOffice: 'Labuan',
        salesDistrict: 'West',
        shippingCond: 'TP',
        accountCreation: '2023-06-01',
        showOnList: 1,
        ifFamilyChannel: 0,
        allowLalamove: 0,
        startingSalesAmt: 2200,
        status: 0,
      },
      // Add 4 more entries as needed...
    ];
  },

  getListEtenMini() {
    return Promise.resolve(this.getListEtenData().slice(0, 5));
  },

  getListEtenSmall() {
    return Promise.resolve(this.getListEtenData().slice(0, 10));
  },

  getListEten() {
    return Promise.resolve(this.getListEtenData());
  },
};